swift-server/async-http-client

- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
`PATCH` is a commonly supported verb in RESTful APIs. Although it is
already possible to send a PATCH request via the `HTTPClient.execute()`
API this commit adds an explicit `patch()` API for consistency.
This gives us explicit APIs for `GET`, `POST`, `PUT`, `PATCH` and
`DELETE`.
> feat: Add HTTPClient.patch() for sending PATCH requests

- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
This PR publicize's `HTTPClient`'s event loop group. Accessing this is critical for creating useful extension to `HTTPClient` that may need to create promises or completed futures. For an example see https://github.com/vapor/vapor/pull/1967/files#diff-b92daaa19da98c2968da06e7226b8fb0R3.
> publicize client's elg

- Package.swift
- Sources/NIOHTTPClient/HTTPClientProxyHandler.swift
- Sources/NIOHTTPClient/HTTPCookie.swift
- Sources/NIOHTTPClient/HTTPHandler.swift
- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
- Tests/NIOHTTPClientTests/HTTPClientTestUtils.swift
- Tests/NIOHTTPClientTests/SwiftNIOHTTPTests+XCTest.swift
- Tests/NIOHTTPClientTests/SwiftNIOHTTPTests.swift
This solves a bug that could cause infinite redirections (eg: requesting example.com, being redirected to www.example.com, but requesting again example.com as host hadn't been correctly modified).
> Transfer scheme and host to new request when redirected

- scripts/generate_docs.sh
Since the package isn't tagged yet, the current file prefix URL isn't valid, causing the declarations "Go to GitHub" button to lead to a 404 page.
> Solve incorrect "Show on GitHub" link

- Sources/NIOHTTPClient/HTTPHandler.swift
- Tests/NIOHTTPClientTests/SwiftNIOHTTPTests.swift
Since we don't have a connection pool, we need to close `channel` after request is processed, this PR addresses #33
> close connections after request is processed

- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
motivation: elg provider is a likely to be a common pattern in client libraries (like db drivers etc), lets prevent type clashes
changes: make EventLoopGroupProvider a nested class of HTTPClient
> move elg provider as a nested class of the client

- README.md
- Sources/NIOHTTPClient/HTTPHandler.swift
- Sources/NIOHTTPClient/RequestValidation.swift
- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
- Sources/NIOHTTPClient/Utils.swift
- Tests/NIOHTTPClientTests/HTTPClientTestUtils.swift
- Tests/NIOHTTPClientTests/SwiftNIOHTTPTests+XCTest.swift
- Tests/NIOHTTPClientTests/SwiftNIOHTTPTests.swift
Addressing comments in the client proposal discussion, I would like to propose the following change:
`HTTPResponseDelegate.didReceivePart` now returns an optional future that could be used to indicate to the client that reads should be stopped until this future is resolved (backpressure)
`HTTPClient.Body` is now a struct with optional length and a callback for upload streaming. In addition, there are static methods to keep API the same as before.
> Upload streaming

- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
`timeout` was never being passed along to `execute` so `execute` would always fallback to the timeout from `configuration`.
> Pass timeout from get/post/patch/put/delete to execute

- README.md
This pull request contains just the README fixes from my previous pr #41.
The current example doesn't compile anymore because:
- HTTPResponseDelegate has been renamed to HTTPClientResponseDelegate
- HTTPRequest has been renamed HTTPClient.Request
> fix compile errors in README example

- Sources/NIOHTTPClient/HTTPHandler.swift
- Tests/NIOHTTPClientTests/HTTPClientTestUtils.swift
- Tests/NIOHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/NIOHTTPClientTests/HTTPClientTests.swift
This is a fix for issue #42
Previously when you made HTTP requests to a route with percent encoding, the encoding would be removed causing the request to fail. 
This request adds the percent encoding back to the path when you get the uri so that it can be correctly processed.
> feat: Add support for percent encoded requests

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
As discussed in #54, currently if using a shared event loop group object to create a `HTTPClient`, the `eventLoop` property of the `Channel` will most likely not be the same as the `eventLoop` property of the `Task`. This can lead to a precondition failure, when the task delegate hops to the the task`s event loop.
This patch makes sure that both the task and the connection (channel) share the same event loop instance.
It also add a precondition on `Task.setChannel(_:)` to verify that the channel uses the same event loop as the task.
The provided test would trigger the `precondition` failure if the event loops would not match.
> Make sure that event loop of task is the same as event loop of channel

- Sources/NIOHTTPClient/SwiftNIOHTTP.swift
- Tests/NIOHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/NIOHTTPClientTests/HTTPClientTests.swift
Add deadline argument to API methods
> add deadlines

- docker/Dockerfile
- docker/docker-compose.1804.50.yaml
motivation: better alignment with community
changes: use the official swift docker images instead of hand rolled ones
> use official swift images

- README.md
See https://github.com/swift-server/async-http-client/issues/69 for details. Some of the code snippets provided in `README.md` were not quite correct
> Addressing README.md code snippets as per issue#69

- .swiftformat
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- docker/Dockerfile
- scripts/sanity.sh
motivaiton: unified format
changes:
* fix outstanding formatting issues
* add a call to swiftformat as part of sanity script
* fix sanity script language check debugging statements
> test formatting issues as part of sanity check

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
motivation: safer handling of request validation and mutation
changes:
* fix schema logic to be non-case sensitive
* made request version, method and url immutable
* made request scheme and host internal
* adjusted redirect ahndler implementation to stricter request immutabllity
* adjust and add tests
> improve request validation

- Sources/AsyncHTTPClient/HTTPHandler.swift
Hi there,
I want custom `ResponseAccumulator` delegate like https://github.com/swift-server/async-http-client/pull/74#issuecomment-518506014 , so can we public init function for `HTTPClient.Response`? please review it if we can.
> Add init to HTTPClient.Response

- Sources/AsyncHTTPClient/HTTPHandler.swift
The only place where this method is currently called uses its return
value, but that's specific to the context where it's used (inside of
chained calls to map/flatMap). Future uses might not always need to use
the return value since it is the same as what's passed as the method
argument.
> Add @discardableResult to HTTPHandler setChannel method

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Hi there,
I think we should ignore uncleanShutdown when state is `.head` or `.body`, please review it. thx.
> Ignore uncleanShutdown error when state is .head or .body

- README.md
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
fixes #83 (JW: I made this `fixes` instead of `addresses` because that's a magic word to github which will auto close #83 once this is merged).
> rename didReceivePart to didReceiveBodyPart

- README.md
- README suggested that you should shut down the client in a `defer` block right after calling `get` which will not actually work because the `get` is asynchronous so returns before it's done
- README said that if you share the `EventLoop` you don't need to shut down the `HTTPClient` which is not true
- README didn't make it clear that using `HTTPClient(eventLoopGroupProvider: .createNew)` is an acceptable thing to write in many places but it's really resource inefficient
> fix README: fixed a couple of documentation mistakes

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
> add NIO event loop as an argument for execute

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
See https://github.com/swift-server/async-http-client/issues/88 for details
> redirects ignore EventLoop preference - issue#88

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPClientProxyHandler.swift
motivation: make proxy configuration follow same convention as other configuration
changes:
* nest Proxy under HTTPClient.Configuration instad of top level HTTPClient
* make host and port public and mutable, following convention of other configuration objects in this library
* add some API docs
> refactor proxy configuration

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
> nest timeout configuration type inside configuration

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Right now, HTTPClient only asserts that it's shut down if it was started with its own EventLoopGroup.
That however is weird because it's lifecycle model depends on the parameters you pass to `init`.
Modifications:
Always validate the lifecycle (in debug mode).
Result:
- API makes more sense.
- this is especially important once we get a connection pool, don't want to have the connections sitting around forever without the possibility of every being used again.
> make sure HTTPClient is shutdown

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
This commit should fix #95 and adds associated tests
> Tolerate futures from arbitrary event loops

- .swiftformat
- Sources/AsyncHTTPClient/HTTPClientProxyHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
This is a question of preference, but it looks like the most commonly used format for ranges in Swift projects is what can [be found in the Swift Book](https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html) where there is no space between the values and range operators, for instance: `case 200..<300:` contrary to the current `case 200 ..< 300`.
What do you think? 🙂
> Remove spaces in range operators

- Package.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
With #96 we changed `HTTPClient.Task`'s `eventLoop` property to be `currentEventLoop` because we anticipated that it might change because of the connection pool work that's ongoing.
That however made the programming model rather hard because the user didn't get any guarantee anymore on which `EventLoop` the delegate would run.
With this patch, we're bringing `eventLoop` back which is the `EventLoop` the delegate will run on. Note that it's not necessarily the `EventLoop` the `Channel` will run on. If the user requires those to be the same, the can request that with `EventLoopPreference.delegateAndChannel(on: eventLoop)` rather than `.indifferent` or `.delegate(on: eventLoop)`
Modification:
Let the user select between:
- `.indifferent`: I don't care about the `EventLoop`
- …
> EventLoop preference overhaul

- Sources/AsyncHTTPClient/HTTPHandler.swift
> cancel should be done with outbound user event

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
We're getting ready for 1.0.0 so we should remove all the deprecations.
- fixes #108
> remove all deprecations

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
This PR adds support for 2 types of redirect limits - one that detects loops (by keeping history of all visited URL's for a single request), and one that just counts the number of redirects.
fixes #76
> add support for redirect limits

- README.md
Following the release of async-http-client 1.0.0, the dependency to add in Package.swift is now bumped too.
> Update dependency given in README to 1.0.0

- docker/Dockerfile
- docker/docker-compose.1804.50.yaml
- docker/docker-compose.1804.51.yaml
- docker/docker-compose.yaml
- scripts/check_no_api_breakages.sh
motivation: better ci testing
changes:
* add api breakage script to test api breakage in ci
* add "shell" utility docker-compose task to run api breakage script
* change test task to treat warning as errors
* change test task to use thread sanitizer in 5.1
> test with thread sanitizer and check for api breakage in ci

- CONTRIBUTING.md
- CONTRIBUTORS.txt
- Package.swift
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPClientProxyHandler.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/LinuxMain.swift
- scripts/check_no_api_breakages.sh
- scripts/generate_contributors_list.sh
- scripts/generate_docs.sh
- scripts/generate_linux_tests.rb
- scripts/sanity.sh
motivation: the Swift Server Workgroup is not a legal entity and cannot hold copyrights. with this change, code authors continue and retain their copyrights under the apache license and previous copyrights note, but Apple steps up instead of the workgroup which has no legal status
changes:
* update header files to say "Apple Inc. and the AsyncHTTPClient project authors" instead of "Swift Server Workgroup and the AsyncHTTPClient project authors"
* update validation scripts to check for the correct header
* add CONTRIBUTING.md file to explain how to make contributions and include a legal notice about licensing the contribution to Apple and the project
* regenerate CONTRIBUTORS.md to refelct most recent contributions
> update copyrights note

- Package.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
More unit tests are good and now that SwiftNIO shipd
`NIOHTTP1TestServer`, writing integration tests for async-http-client is also
more straightforward.
Modification:
Demonstrate some tests using NIOHTTP1TestServer.
Result:
More tests.
> a set of extra test cases

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
It's important to also have a test case where async-http-client is
actually used to do multiple parallel requests on multiple workers.
Modification:
Add a test where 5 workers are doing 100 requests each.
Result:
Better test coverage.
> add a parallel test case

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
We need a test that we can handle servers that repeatedly send
connection: closes.
Modification:
Add a unit test that always makes the server send connection: close.
Result:
More test coverage.
> add test where server sends connection: close

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Solving the SNI Bug
Modifications:
Added an internal extension on String for checking if the hostname is an IP Address -- see the private extension on SNI. Additionally using the IPv4Address and IPv6Address Function from Network above 10.14 as protecting with #availabe.
Adding the test for HTTPS and IP in as hostname
Result:
We get results with an IP as Hostname
> Bugfix HTTPS SNI and IP Address

- Sources/AsyncHTTPClient/Utils.swift
**Fixed issue:**
The #139 bug fix is unfortunately not compatible with older (< macOS 10.14) Apple platforms versions where the `Network` framework didn't have the `IPv4Address` and `IPv6Address` types yet.
**Solution:**
Use the UNIX implementation across all platforms to avoid unnecessary
complexity introduced by platform specific implementations.
**Alternative solutions:**
Runtime OS version checks dispatching the calls to the right implementation could also work but seem unnecessarily complicated compared to simply using the UNIX version everywhere.
> Remove parts of #139 relying on the Network framework

- Sources/AsyncHTTPClient/Utils.swift
`HTTPClientCopyingDelegate` meant to be public, hence make the initializer public.
> Make public class public constructable

- Sources/AsyncHTTPClient/HTTPHandler.swift
As discussed in #128. We make the ResponseAccumulator public to give developers an easy time to create a Task. With the ResponseAccumulator the developer using this does not have to worry, about implementing the HTTPClientResponseDelegate all by himself.
> ResponseAccumulator is now public

- docker/docker-compose.1604.51.yaml
- docker/docker-compose.yaml
motivation: more secured ci setup
changes:
* enable :z selinux flag on bind mounts so we can enable selinux on ci
* drop potentially exploitable capabilities from docker-compose
* create a 16.04 docker-compose setup so we can run tsan in ci (broken on 18.04)
> enable tsan and improve docker security

- docker/docker-compose.1604.51.yaml
motivation: 16.04 docker-compose setup was pulling 18.04 by mistake
changes: use xenial instead of bionic
> actually use 16.04 on 16.04 builds

- Sources/AsyncHTTPClient/HTTPHandler.swift
Closes #158 by adding a public init to `StreamWriter`
Motivation:
Even though `StreamWriter` is public, its init is not, that makes using it in tests impossible.
Modifications:
add public `init` to `StreamWriter`
Result:
`StreamWriter` can no be instantiated by the clients of the library
> add a public init to StreamWriter

- Sources/AsyncHTTPClient/HTTPHandler.swift
Motivation:
Generally, most members in `struct`s should be `var` but in this particular case, `let` makes more sense (for now) because there are other properties (like `kind`) that are generated from things like host/port/scheme. If we allow `scheme` to become `var`, then we would need to update `kind` when changed, however that wasn't done.
Also, the `var` functionality wasn't tested and therefore we should restore the behaviour of 1.0.1 which was to store them as `let`s.
Modification:
make the `method`, `url`, and `scheme` members of `Request` a `let`.
Result:
Harder to make an illegal `Request` value.
> some lets in Requests were vars by accident

- Package.swift
This is not strictly necessary because `swift package update` will fix the issue anyway but I think it's always good style to have the `Package.swift` require a secure version.
- https://nvd.nist.gov/vuln/detail/CVE-2019-15605
- https://forums.swift.org/t/swiftnio-security-releases-2-13-1-and-1-14-2/33671
> require secure NIO version

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Previously, UNIX Domain Sockets would only work if the URL also had a
"base URL". If it didn't have a base URL, it would try to connect to the
empty string which would fail :).
Now, we support both cases:
- URLs with a baseURL (the path to the UDS) and a path (actual path)
- URLs that just have an actual path (path to the UDS) where we'll just
use "/" as the URL's path
> fix UDS without a baseURL

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
I wasn't sure if we tested that we would successfully recover from
a server that sometimes closes the connection on us.
Modification:
Added a test case where we do three requests: First one succeeds,
second one gets a close from the server, third one succeeds again.
So we're testing that although AsyncHTTPClient doesn't auto-retry, the
user can just retry again.
Result:
More test coverage.
> add extra test case

- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
Motivation:
I wasn't sure if we actually properly observed an idle connection
suddenly closing. Ideally, if an idle connection just goes away, we just
want to remove it from the connection pool (which is what happens).
Modification:
Add a test that verifies idle connections that get closed from the
server don't get reused in the pool.
Result:
Better test coverage for more complicated scenarios.
> test that connection close whilst idle works

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation: Pooled connections should close at some point (see #168)
Changes:
- Add new `maximumAllowedIdleTimeInConnectionPool ` property to `HTTPClient.Configuration`, its default value is currently `.seconds(60)`, and it can be set to `nil` if one wishes to disable this timeout.
- Add relevant unit test
- Closes #168
> Close idle pool connections

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
motivation:
TLS handshake promise was leaked in some cases of failure (fixes #179)
changes:
- Avoid leaking promise
- Clearer completion flow for related futures
- Add testAvoidLeakingTLSHandshakeCompletionPromise test
> Fix leaked TLS handshake promise

- Sources/AsyncHTTPClient/HTTPHandler.swift
Add HTTP version to response struct. Closes #164 
Motivation:
Servers are free to respond with different versions in some cases, clients need to have access to returned version.
Modifications:
Copy HTTP version from `.head` part to `Response` struct on init.
Result:
Clients of the library now have access to returned HTTP version.
> add version to response

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Fix `Location` header case-sensitive lookup, closes #185 
Motivation:
HTTP Header names are case-insensitive.
Modifications:
Use `.first` method provided by `HTTPHeaders`
Remove `cookieHeaders` method and instead use getter provided by `HTTPHeaders`
Result:
Redirects will now be processed correctly.
> fix location header lookup

- .swiftformat
- docker/Dockerfile
- docker/docker-compose.1604.51.yaml
- docker/docker-compose.1804.52.yaml
- docker/docker-compose.1804.53.yaml
motivation: 5.2 adoption, prepare for 5.3
changes:
* use 5.2 docker-compose setup
* add 5.3 docker-compose setup (placeholder)
* update format
> update ci setup

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Hi 👋, thanks for all the great work on this project.
I have a package that calls the Travis API, which uses %2F as part of the URL path segment. This PR adds a test case & migrates to `URLComponents(url: self, resolvingAgainstBaseURL: false)?.percentEncodedPath` which covers that use case.
I also updated the test server to switch on the `percentEncodedPath` so it's easier
to understand the desired behaviour. I've tested this locally on 10.15.4 but not on Ubuntu.
> Enable clients to call URLs that include %2F as an escaped backslash

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests.swift
Make cookie parsing case-insensitive, closes #205
Motivation:
As per https://tools.ietf.org/html/rfc6265#section-5.2.2, cookie names should be case-insensitive, and currently they are not.
Modifications:
1. always split cookie component into name and optional value, lowercase the name and then match by this name using pre-defined lowercased constant
2. modify one of the tests to send differently-cased cookie components
Result:
Cookie parsing is case-insensitive.
> make cookie parsing case insensitive

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests.swift
Allow empty-value cookies, closes #206 
Motivation:
RFC allows empty-value cookies, so we should handle them as well
Modifications:
1. Fix split in cookie parsing
2. Add a test
Result:
We can now allow empty value cookies
> allow empty value cookies

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientCookieTests.swift
Fixes malformed cookie parsing, closes #209.
Motivation:
We do not check that cookie component name could be empty, assuming that split array is not empty, that could lead to crash.
Modifications:
1. return empty pairs if split array is empty
2. add a test
Result:
Cookie parsing is more robust.
> fix malformed cookie parsing

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
We didn't have a test that tested that streaming really streams, ie.
that request body part N arrives before N+1 is sent.
Modification:
Test it.
Result:
Better test coverage.
> test: that streaming actually works

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fixes request validation error propagation and use-after-shutdown, closes #217 and #220.
Motivation:
First issue is that validation errors are not passed to task fail methods. Second is that channel closed before connection is released from the pool, in this case clients will get wrong error (`remoteConnectionClosed`) and connection will be released twice, potentially trying to execute stuff on a shutdown event loop.
Modifications:
1. use task failing method for error propagation
2. close channel after connection was released
Result:
Error propagation is fixed.
> fix validation error propagation

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fixes programming model for upload streaming
Motivation:
Right now EL on which we execute streaming call back is not explicitly defined. Also, we do not check on which EL part write is executed, meaning we can fail if `.write` is not called on correct EL.
Modifications:
1. Call to `body.stream` is now executed on tasks EL
2. Calls to `writeAndFlush` are always called on channel EL
3. Added tests for those to cases
4. Removed a hack in test introduced in #219 
5. Fixed #219 shutdown to not call to shutdown EL
Result:
1. closes #198
2. closes #200
> draft for streaming el fixes

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Previously, we'd only use the server's connection header to determine if
we should close the connection or not. That's wrong because if we set
`connection: close` ourselves, we must not reuse again.
Modification:
Set `TaskHandler.closing = false` if we send a close header.
Result:
More HTTP correctness.
> cpool: don't reuse connection if we sent close

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
These changes upgrade the unix domain socket handling to address the following issues:
- Using socket paths currently requires obtuse URL objects with a specially constructed baseURL. These are not easily serializable as strings.
- It is currently not possible to connect to a server over a socket path that uses TLS.
To maintain backward compatibility, this PR introduces two new URL schemes: `http+unix://`, and `https+unix://`. These url schemes, while not universal, are used in a standard way by other services ([some](https://github.com/httpie/httpie-unixsocket) - [examples](https://github.com/msabramo/requests-unixsocket)), and work by %-encoding the socket path as the url hostname. These are easy to construct using standard swift types:
```swift
let socketURL = URL(string: …
```
> Better support for UNIX Domain sockets

- .swiftformat
- Package.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/NoOpLogHandler.swift
- Sources/AsyncHTTPClient/StringConvertibleInstances.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- docs/logging-design.md
Motivation:
AsyncHTTPClient is not a simple piece of software and nowadays also
quite stateful. To debug issues, the user may want logging.
Modification:
Support passing a logger to the request methods.
Result:
Debugging simplified.
Example `.debug` logs:
```
2020-05-27T18:22:07+0100 debug: ahc-request=GET http://localhost:50006/not-found/request/GET) ahc-connection=SocketChannel { BaseSocket { fd=16 }, active = true, localAddress = Optional([IPv4]127.0.0.1/127.0.0.1:50008), remoteAddress = Optional([IPv4]127.0.0.1/127.0.0.1:50006) } ahc-request-id=0 ahc-channel-el=SelectableEventLoop { selector = Selector { descriptor = 3 }, thread = NIOThread(name = NIO-ELT-0-#0) } req=yo-GET ahc-task-el=SelectableEventLoop { selector = Selector { descriptor = 3 }, thread = NIOThread(name = …
```
> logging support

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionsState.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift
Fixes some edge cases in shutdown and pending states.
Motivation:
There are two issues this PR addresses:
1. Flaky test, where we are trying to close the client when connection was able to `enqueue` and get an unexpected error
2. The fact that provider is created with `+1` pending state, while it might not be an error, it makes testing difficult, also might lead to races in shutdown.
Modifications:
1. `HTTP1ConnectionsProvider` is no longer created with `+1` pending
2. If we receive `close` while request is enqueued, it should be failed with a more expected `.alreadyShutdown` error, since its the only way to get into that state, so test was actually catching the right thing.
Result:
Closes #226 
Closes #323
> Refactor provider shutdown and pending flows

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Add tests that execute delegate backpressure call-ins on a different EL
Motivation:
Programming model: all call-outs and call-ins have to be on the task EL, we need to add a safeguard so it would not be accidentally broken.
Modifications:
Adds a test that calls-in on a different EL
Result:
Closes #222
> add callin tests

- Sources/AsyncHTTPClient/ConnectionsState.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests+XCTest.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
Fixes a crash in `testUncleanCloseThrows`.
Motivation:
This PR aims to fix two issues:
1. A crash on precondition, that was not removed when I re-factored how shutdowns work, it is absolutely normal to get a connection failure when client is shutting down, for example in the following scenario:
- send a request that will fail to connect
- shutdown the client
- when connect error will be processed, client will be `.closed`, so it's a completely normal situatuon
2. A racy test, that test tries to establish a connection and shutdown the client while this connection is alive. But it does so in a racy fashion, there is no guarantee that when we get to client shutdown, connection has been established. This will be addressed by using `NIOHTTP1TestServer`, where we wait for `.head` before we …
> fix test and a crash when closed

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
See https://tools.ietf.org/html/rfc7230#section-5.4
- If port is not 80 or 443 then add to host header.
- Fixed up tests
> The host header should also include the port

- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fixes test crashing on precondition.
Motivation:
When tests are executed on macOS client ELG is actually a `NIOTS` ELG, so it's incompatible with `NIOHTTP1TestServer`
Modifications:
Use separate ELG in `testUncleanCloseThrows`
Result:
Closes #256
> fix test faling with NIOTS

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
Adds checking for supplied body length.
Motivation:
We need to guard against incorrect body length since we can re-use connection, this is a potential security issue.
Modifications:
- Adds a check in `HTTPTaskHandler` that if validated headers contain `Content-Length`, user sends exactly that amount of body data.
- Two tests
Result:
Closes #251
> check body length

- Package.swift
Not sure if this is worth opening a PR for, since any new checkouts will never see this issue, and it's only necessary due to tests, so please feel free to close this if it's not necessary.
Motivation:
Due to using new ByteBuffer initializers from https://github.com/apple/swift-nio/releases/tag/2.18.0 in some tests (specifically, `ByteBuffer(string: ...)`), the project will no longer compile if an older version of swift-nio is checked out.
Modifications:
Updated swift-nio from 2.16.0 to 2.18.0.
Result:
SPM should now grab the latest version of swift-nio if this version of async-http-client is used.
> Updated swift-nio to 2.18.0

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fixes flaky test
Motivation:
Test was actually getting `404` and was closing connection too early.
Modifications:
Fix request path.
Result:
Closes #265
> fix flaky testContentLengthTooLongFails test

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionsState.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests+XCTest.swift
- Tests/AsyncHTTPClientTests/ConnectionPoolTests.swift
All internal connection flow should be executed when shutting down.
Motivation:
When we shut the client down, we expect the provider to finish all its tasks, if there are some, and then delete itself and succeed the close promise. Currently, if connection is created unsuccessfully, or available connection is closed/times out before we close it as part of shutdown, those connection will not trigger correct flow.
Modifications:
1. `connectFailed` now triggers correct flow when client is `.closed`
2. `timeout` now triggers correct flow when client is `.closed`
3. `removeClose` now triggers correct flow when client is `.closed`
4. `offer` is refactored
5. Added 4 new tests, that specifically test described scenarios
Result:
Closes #263 
Closes #260
> All internal connection flow should be executed when shutting down

- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fix missing connect timeout and make some tests faster and safer.
Motivation:
1. During pool implementation/refactoring we lost connection timeout, this PR fixes that
2. `testConnectionFailError` is slow, 10 seconds, due to not having a timeout set
3. `testConnectionFailError` and `testTLSVersionError` use dangerous `do-try-XCFail-catch` pattern
Modifications:
1. Set connection timeout if specified
2. Set connect timeout to 150 ms to make `testTLSVersionError` faster
3. Use `XCTAssertThrowsError` in `testConnectionFailError` and `testTLSVersionError`
4. Add general connection timeout test, since `testConnectionFailError` is NIOTS-specific.
Result:
Fixes an issue where connection timeout configuration was not respected, hopefully makes tests more robust
> fix missing connect timeout and make tests safer

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
An arbitrary HTTP(S) server should not be able to trigger redirects, and thus activity, to a local socket-path based server, though the opposite may be a valid scenario. Currently, requests in either direction are allowed since the checks don't actually check the destination scheme.
Modifications:
- Added a method to HTTPBin to redirect to the specified target.
- Added failing tests that perform redirects from a regular server to a socket-based server and vice versa.
- Refactored `hostSchemes`/`unixSchemes` to `hostRestrictedSchemes`/`allSupportedSchemes`, which better describes what they do.
- Refactored `Request.supports()` to `Request.supportsRedirects(to:)` since it is only used by Redirects now.
- Check the destination URL's scheme rather than the current URL's scheme …
> Fixed an issue where redirects to socket path-based servers from any server was always allowed

- Sources/AsyncHTTPClient/HTTPClient.swift
`HTTPClient(eventLoopGroupProvider = .createNew)` is not a valid Swift expression.
> Fix invalid code in `HTTPClient.swift` doc comment

- README.md
Long lines in code snippets make it hard to read, especially on any screen that's not extra-wide, including laptops, tablets and other mobile devices.
> Avoid horizontal scrolling in README.md code snippets

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
> Added default value for queue in HTTPClient.shutdown(queue:callback:)

- Package.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Motivation:
Build warnings fail our builds.
Modifications:
- Update minimum NIOSSL version
- Remove the use of the now-unnecessary `try` statement.
Result:
No warnings!
> Kill build warnings.

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- docker/Dockerfile
Rename pool configuration type and property to `ConnectionPool`
Motivation:
`HTTPConfiguration.poolConfiguration` is redundant and does not make clear what pool are we talking about.
Modifications:
Rename property and type to `ConnectionPool`
Result:
Closes #286
> rename connection pool configuration

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
Prevent TaskHandler state change after `.endOrError`
Motivation:
Right now if task handler encounters an error, it changes state to `.endOrError`. We gate on that state to make sure that we do not process errors in the pipeline twice. Unfortunately, that state can be reset when we upload body or receive response parts.
Modifications:
Adds state validation before state is updated to a new value
Adds a test
Result:
Fixes #297
> Fix state reverting

- scripts/generate_docs.sh
Spotted a last instance of the word "master" in the scripts.
This completes the move to main as the main branch name
> Adjust gen_docs script Default branch is `main`

- Sources/AsyncHTTPClient/ConnectionPool.swift
@weissi made me aware at multiple instances that `el.assertInEventLoop()` should be used over `assert(el.inEventLoop)`, since it ensures that the correct behavior is called for `NIOTSEventLoop`s. 
Replace three instances of `assert(el.inEventLoop)` with `el.assertInEventLoop()`.
> Use assertInEventLoop over assert(el.inEventLoop)

- README.md
- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
A simple test is included, let me know if you'd like it to be more sophisticated.
> Add FileDownloadDelegate for simple file downloads

- README.md
The progress API of `FileDownloadDelegate` changed at the last minute, but the example in `README.md` wasn't updated accordingly.
> Fix FileDownloadDelegate example code in README.md

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Right now we only handle one type of SSL error: `.handshakeFailed`,
but in reality a multitude of errors can happen, for example, remote
party might just close connection that will in turn raise
`.uncleanShutdown` error, that will be dropped on the floor and
users will only get non-descriptive `NoResult` error.
Modifications:
Handle all types of SSL errors during handshake instead of just one.
Adds a test.
Result:
Closes #313
> Fixes propagation of errors during TLS handshake

- Sources/AsyncHTTPClient/HTTPClient.swift
Motivation:
Right now documentation states that timrout defaults to no timeout, this
is no actually true, if timeout is not set NIO bootstrap defaults to 10
seconds connect timeout.
Modifications:
Updates documentation comment.
Result:
Closes #118
> Fixes default timeout documentation comment

- Sources/AsyncHTTPClient/ConnectionPool.swift
Motivation:
Thread safety analyzer reports warning about observable state
leaving lock guarded code blocks. This PR address the warnings.
Analysis of the warning does not prove that we have a real bug and all the
warnings are considered as potential bugs.
Analyzer used is:
`docker run --rm -v $(pwd):/src -w /src swift:5.3.1 swift test -c
release --sanitize=thread --enable-test-discovery`
Modifications:
* accessor to count of connections in connection pool is guarded by lock
* forced materialization of a potentially lazy collection into an array before returning
the collection from lock guarded code block
Result:
Most of thread safety warnings are addressed without modification of observable
code behaviour.
> issue #318: Address warning reported by thread safety analyzer 

- Sources/AsyncHTTPClient/Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Currently when either we or the server send Connection: close, we
correctly do not return that connection to the pool. However, we rely on
the server actually performing the connection closure: we never call
close() ourselves. This is unnecessarily optimistic: a server may
absolutely fail to close this connection. To protect our own file
descriptors, we should make sure that any connection we do not return
the pool is closed.
Modifications:
If we think a connection is closing when we release it, we now call
close() on it defensively.
Result:
We no longer leak connections when the server fails to close them.
Fixes #324.
> Add defensive connection closure.

- .gitignore
- scripts/generate_docs.sh
motivation: fix doc generation - sourcekitten requires Swift 5.2
changes: expose the doc generation task on the 5.3 docker-compose file so we can trigger it there
> fix doc generation setup

- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
Flaky tests are bad.
This test is flaky because the server closes the connection immediately
upon channelActive. In practice this can mean that the handshake never
even gets a chance to start: by the time the SSLHandler ends up
in the pipeline the connection is already dead. Heck, by the time we
attempt to complete the connection the connection might be dead.
Modifications:
- Change the shutdown to be on first read.
- Remove the disabled autoRead.
- Change the expected NIOTS failure mode to connectTimeout,
which is how this manifests in NIOTS.
Result:
Test is no longer flaky.
> Address flakiness of testSSLHandshakeErrorPropagation

- README.md
Adding the product dependency to the target by name only produces an error in Xcode 12.4. Instead, the product dependency should be given as a `.product`. 
This PR updates the README with the new format, so that new user's won't stumble over this.
> Update Readme to account for Package.swift format

- Sources/AsyncHTTPClient/HTTPHandler.swift
Motivation:
HTTPResponseAggregator attempts to build a single, complete response
object. This necessarily means it loads the entire response payload into
memory. It wants to provide this payload as a single contiguous buffer
of data, and it does so by aggregating the data into a single contiguous
buffer as it goes.
Because ByteBuffer does exponential reallocation, the cost of doing this
should be amortised constant-time, even though we do have to copy some
data sometimes. However, if this operation triggers a copy-on-write then
the operation will become quadratic. For large buffers this will rapidly
come to dominate the runtime.
Unfortunately in at least Swift 5.3 Swift cannot safely see that during
the body stanza the state variable is dead. Swift is not necessarily
wrong about this: …
> Fix CoW in HTTPResponseAggregator

- Package.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/Utils.swift
Motivation:
There is an awkward timing window in the TLSEventsHandler flow where it
is possible for the NIOSSLClientHandler to fail the handshake on
handlerAdded. If this happens, the TLSEventsHandler will not be in the
pipeline, and so the handshake failure error will be lost and we'll get
a generic one instead.
This window can be resolved without performance penalty if we use the
new synchronous pipeline operations view to add the two handlers
backwards. If this is done then we can ensure that the TLSEventsHandler
is always in the pipeline before the NIOSSLClientHandler, and so there
is no risk of event loss.
While I'm here, AHC does a lot of pipeline modification. This has led to
lengthy future chains with lots of event loop hops for no particularly
good reason. I've therefore replaced …
> Use synchronous pipeline hops to remove windows.

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
AsyncHTTPClient attempts to avoid the problem of Happy Eyeballs making
it hard to know which Channel will be returned by only inserting the
TLSEventsHandler upon completion of the connect promise. Unfortunately,
as this may involve event loop hops, there are some awkward timing
windows in play where the connect may complete before this handler gets
added.
We should remove that timing window by ensuring that all channels always
have this handler in place, and instead of trying to wait until we know
which Channel will win, we can find the TLSEventsHandler that belongs to
the winning channel after the fact.
Modifications:
- TLSEventsHandler no longer removes itself from the pipeline or throws
away its promise.
- makeHTTP1Channel now searches for the TLSEventsHandler from the …
> Unconditionally insert TLSEventsHandler

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/ResponseReadBuffer.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- scripts/soundness.sh
Motivation:
Users of the HTTPClientResponseDelegate expect that the event loop
futures returned from didReceiveHead and didReceiveBodyPart can be used
to exert backpressure. To be fair to them, they somewhat can. However,
the TaskHandler has a bit of a misunderstanding about how NIO
backpressure works, and does not correctly manage the buffer of inbound
data.
The result of this misunderstanding is that multiple calls to
didReceiveBodyPart and didReceiveHead can be outstanding at once. This
would likely lead to severe bugs in most delegates, as they do not
expect it.
We should make things work the way delegate implementers believe it
works.
Modifications:
- Added a buffer to the TaskHandler to avoid delivering data that the
delegate is not ready for.
- Added a new "pending close" state …
> Better backpressure management.

- Package.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
The way NIOSSL propagated TLS handshake fails was incorrect. This was fixed and released in NIOSSL 2.12.
This PR updates to NIOSSL 2.12.x, and fixes tests that were broken as part of the change.
> Update to NIOSSL 2.12.x and fix tests

- docker/Dockerfile
- docker/docker-compose.2004.54.yaml
motivation: 5.4 is out!
changes:  add docker compose setup for ubuntu 20.04 and 5.4 toolchain
> add 5.4 docker setup for CI

- Package.swift
- Sources/AsyncHTTPClient/BestEffortHashableTLSConfiguration.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Adds support for request-specific TLS configuration:
`Request(url: "https://webserver.com", tlsConfiguration: .forClient())`
https://github.com/apple/swift-nio-ssl/pull/280 must be released, before this can be merged.
> Support request specific TLS configuration

- .dockerignore
- Sources/AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
This PR is a result of another #321.
In that PR I provided an alternative structure to `TLSConfiguration` for when connecting with Transport Services. 
In this one I construct the `NWProtocolTLS.Options` from `TLSConfiguration`. It does mean a little more work for whenever we make a connection, but having spoken to @weissi he doesn't seem to think that is an issue. 
Also there is no method to create a `SecIdentity` at the moment. We need to generate a pkcs#12 from the certificate chain and private key, which can then be used to create the `SecIdentity`.
This should resolve #292
> Generate trust roots SecCertificate for Transport Services

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/SSLContextCache.swift
- Tests/AsyncHTTPClientTests/SSLContextCacheTests+XCTest.swift
- Tests/AsyncHTTPClientTests/SSLContextCacheTests.swift
Motivation:
In the vast majority of cases, we'll only ever create one and only one
`NIOSSLContext`. It's therefore wasteful to keep around a whole thread
doing nothing just for that. A `DispatchQueue` is absolutely fine here.
Modification:
Run the `NIOSSLContext` creation on a `DispatchQueue` instead.
Result:
Fewer threads hanging around.
> SSLContextCache: use DispatchQueue instead of NIOThreadPool

- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
Motivation:
Swift Package Index builds for i(Pad)/tvOS are currently failing because the tests access a method that's only available on iOS12+.
Modification:
Put in the right availability check.
Result:
Should compile in Swift Package Index
> fix Swift Package Index build

- README.md
- SECURITY.md
The updated [SSWG security requirements](https://github.com/swift-server/sswg/blob/main/security/package-requirements.md) require that listed projects have a `SECURITY.md` detailing their security process.
> publish security process

- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Currently the `DelayOnHeadDelegate` test utility depends on correct timings. Right now, if a request is slower than 50ms in  `testErrorAfterCloseWhileBackpressureExerted` the test will fail, since the backpressure promise is failed, before a head was received. This pr fixes this, by giving the user a callback, when the head was received.
> Make DelayOnHeadDelegate resilient

- Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
- Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
The misbehaving SOCKS server test was previously passing, but not for the right reason. The invalid data we were sending was never making it off the server thanks to the SOCKSServerHandshakeHandler.
In fact, as long as SOCKSServerHandshakeHandler is present, it isn't possible to send invalid data. So to test the client now we have to add a completely new handler, which exists only to write some nonsense bytes.
The test still passes, but for the right reason, and we now assert the type of error the client throws too.
> Fix test for misbehaving server

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- The `testSSLHandshakeErrorPropagation` has a very short connect timeout (100ms). The reason for this is, that a failing TLS handshake manifest in NIOTS as a connect timeout and we don’t want to wait for the timeout for to long in our tests.
- When using `NIOSSL` however, we expect a proper `NIOSSLError`. Sometimes though the connection is not setup fast enough (because of the very short 100ms connect timeout), that we get a `connectTimeout` error instead. See build logs: https://ci.swiftserver.group/job/async-http-client-swift52-prb/480/console
```
Test Case 'HTTPClientTests.testSSLHandshakeErrorPropagation' started at 2021-06-22 19:14:49.426
/code/Tests/AsyncHTTPClientTests/HTTPClientTests.swift:2735: error: 
HTTPClientTests.testSSLHandshakeErrorPropagation : failed - Handshake failed …
```
> Make `testSSLHandshakeErrorPropagation` less flaky

- Package.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/Utils.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/SSLContextCacheTests.swift
Updated:
- NIO
- NIOSSL
- NIO Extras
- NIOTS
Also fix `TLSConfiguration.forClient()` warnings by converting to `TLSConfiguration.makeClientConfiguration()`. Also the same for `forServer()`.
> Update NIO family dependencies to 5.2+ versions and fix deprecations

- Package.swift
- Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
This PR adds http/2 support to the `HTTPBin` test utility.
This PR adds `swift-nio-http2` as a dependency.
- Removed obscure initialization options for `HTTPBin`          
- `channelPromise: EventLoopPromise<Channel>? = nil` was only used once (in `testUploadStreamingBackpressure`).
- `connectionDelay: TimeAmount = .seconds(0)` was never used
- `maxChannelAge: TimeAmount? = nil` was never used
- The initialization options `ssl: Bool = false, compress: Bool = false, refusesConnections: Bool = false` have moved into a `Mode` enum. The mode might be `.http1_1(ssl: Bool, compress: Bool)`, `.http2(compress: Bool)`, or `.refuse`
- Added support for `http/2` (not used in any test yet, however I verified the support with curl locally.)
- channel pipeline modifications are nearly all synchronous. …
> Add http/2 support to HTTPBin

- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutingRequest.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestFramingMetadata.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
Currently the request validation (mainly checking for correct headers is sprinkled around). This makes reuse in new code hard.
- Refactored code from `TaskHandler` into new method `HTTPClient.Request.createRequestHead` that creates an `HTTPRequestHead` and matching `RequestFramingMetadata`
- Added required property `requestFramingMetadata` to `HTTPExecutingRequest`
- Added property `requestFramingMetadata` to `RequestBag`
> Refactor Request Validation

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Use the previously introduced type `NegotiatedProtocol` instead of the unhandy tuple `(Channel, HTTPVersion)`
- Tidy code
> ConnectionFactory: Replace (Channel, HTTPVersion) with NegotiatedProtocol

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
In our `HTTPConnectionPool.StateMachine` we want to manage HTTPConnection states. However, to ensure that our state machine reflects the outside world it is beneficial if the state machine would hold references to the actual existing connections. Exposing our Connection types directly to the state machine could lead to abuse though. Developers might call actions directly on the Connection within the state machine.
- Add a `HTTPConnectionPool.Connection` type that is a box around an actual connection. The purpose of the box is to ensure no actions are invoked on the connection within the state machine. Further the box can be used for testing the state machine without creating actual connections.
- This PR doesn't add any tests. This code will be thoroughly tested once the actual state …
> Add HTTPConnectionPool Connection as a box type

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Waiter.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+WaiterTests.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Scheduling a request on the new `ConnectionPool` will require a request to be schedulable _and_ executable. In fact there should never be a request that is schedulable but not executable. For that reason the renamed `HTTPSchedulableRequest` depends on `HTTPExecutableRequest`.
- Rename: `HTTPExecutingRequest` -> `HTTPExecutableRequest`
- Rename: `HTTPSchedulableRequest` -> `HTTPScheduledRequest`
- `HTTPSchedulableRequest` requires `HTTPExecutableRequest`
> HTTPSchedulableRequest requires HTTPExecutableRequest 

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2IdleHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionEvent.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2IdleHandlerTests.swift
- It is unclear what it means to cancel a connection
- Rename `cancel` connection to `shutdown`, with an explicit code comment
- Add `.http1_1` and `.http2` cases to `HTTPConnectionPool.Connection`
> Cleanup: Connection cancel -> shutdown

- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
The `HTTPEchoHandler` has a property `var promises: CircularBuffer<EventLoopPromise<Void>>` that is currently accessed without lock from different eventLoops (`self.serverGroup` and `self.defaultClient.eventLoopGroup`). This in itself may not be a problem. However testing bi directional streaming should not depend on shared promises. Instead the client should write something to an echo server, wait for the body to be echoed and write some more.
- bi directional streaming, writes and reads from an echo server.
No weird shared state in promises between client and server.
> Fix bi directional streaming test

- docker/Dockerfile
The Swift 5.3 CI currently fails with the error:
```bash
ERROR:  Error installing jazzy:
The last version of jazzy (>= 0) to support your Ruby & RubyGems was 0.13.7. Try installing it with `gem install jazzy -v 0.13.7`
jazzy requires Ruby version >= 2.6.3. The current ruby version is 2.5.0.
```
Example log: https://ci.swiftserver.group/job/async-http-client-swift53-prb/338/console
- Explicitly set jazzy version number
Happy Swift 5.3 CI
> Fix CI for Swift 5.3

- Sources/AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift
tls_protocol_version_t was introduced in macOS 10.15 / iOS 13.0, so we need to annotate it with proper availability.
> Add missing availability to APIs requiring macOS 10.15 / iOS 13.0

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
Currently we have a `var eventLoopPreference: HTTPClient.EventLoopPreference` requirement on `HTTPSchedulableRequest`. Sadly in the `.indifferent` case the `HTTPSchedulableRequest` does not expose an eventLoop to create a connection on.
- Replaced the `var eventLoopPreference: HTTPClient.EventLoopPreference` on the `HTTPSchedulableRequest` with `var requiredEventLoop: EventLoop?` and `var preferredEventLoop: EventLoop`
We don't need to hold an `EventLoopGroup` in the `ConnectionPoolStateMachine`.
> [HTTPSchedulableRequest] EventLoop preferences

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
Currently active connections are just closed on shutdown. We expect running requests to be cancelled though.
- Trigger the correct method on `HTTPConnectionPool.Connection` to cancel the request and close the connection then
- Add a test
A better behaving http client.
> Ensure the HTTPConnectionPool calls shutdown on active connections.

- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
There are a number of tests in `HTTPClientInternalTest` that are hard to reproduce after the refactor. The current implementation has a number of (`internal`) properties that will be removed with the refactor. For example there is a way to access the underlying channel from a request today. We don't want to expose those things in a new implementation. But we want to test at least the same things. For this reason I added some tests around sudden HTTP/1.1 connection closures that we want to use going forward.
- Moved `MockConnectionDelegate` to HTTP1ConnectionTests.swift, where it is actually used.
- Added tests around sudden connection closures
Easier test after the implementation has been switched over.
> Add tests to observe HTTP/1.1 connection closures

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
We have some tests that make it hard to see the reason for a test failure. Since `HTTPClientError` is equatable, let's use `XCTAssertEqual`
- Use `XCTAssertEqual` to compare `HTTPClientError`s
- Don't call some server on the internet expecting it will not respond. Create a server and shut it down directly, use the now unused port.
- Better diagnostics on failing tests
- Less outside dependencies on tests
> Improve HTTPClient tests

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
If we can't establish a connection to a remote for the user, we will retry to create the connection. Eventually the requests connection timeout will fire, and we will fail the request. Right now we fail the request always with the `HTTPClientError.getConnectionFromPoolTimeout` error. While this is very descriptive, it does not tell the user if there are to many waiting requests or if there was a connection problem.
- If errors occur during connection creation, we will save the error in the state machine
- If a request times out, after we have seen a connection creation error, we will fail the request with the connection creation error.
If user have a typo in their url, they will get better errors. (dns failure)
> [ConnectionPool] Preserve connection errors

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
In the `HTTP1ConnectionStateMachine` we set the connection state to `.closed` after having forwarded an error to the inner RequestStateMachine. Since we set the error to close, the `state.modify` function did not create an action that would close the connection.
- Modify the ConnectionState based on the RequestStateMachine only in the `state.modify` function.
- Add a test to verify the fixed behavior.
- Use ExpressibleByDictionaryLiteral syntax for some HTTPHeaders to increase readability.
Connections are closed, if an error happens, while we are in a request.
> HTTP1Connection: Close on error while in request

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
If we call 
```
context.write(ByteBuffer(string: "foo"), promise: nil)
context.flush()
context.close()
```
there is no guarantee that `"foo"` will be written to the network. Currently the test `testNoBytesSentOverBodyLimit` assumes this however.
- `testNoBytesSentOverBodyLimit` does not assume anymore, that bytes will be sent before a close of the connection.
- Use `XCTAssertEqual` to compare `Equatable` errors.
> Fix potentially flaky `HTTPClientTests.testNoBytesSentOverBodyLimit`

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/RequestBag.swift
To debug the new `HTTPConnectionPool` and `Connections`, it would be great to get a rather complete event story.
- Added a number of trace logs
- Added a nicer debug output for `Connection.Key`
A better debuggable AHC client.
> Add logging to the new HTTPConnectionPool

- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine+Demand.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
NIO may send `channelRead` events without a handlers requesting more data with a `context.read()` invocation. This happens if the remote has closed the connection and NIO wants to inform the handlers as soon as possible.
- Don't `precondition` on `channelRead` events anymore.
- Close channel if we received an http end without a `context.read()` invocation
> ChannelRead because of closing connection: Remove preconditions

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Currently we don't close connections if we receive an HTTP/1.0 response but no keep-alive header.
- Use `HTTPResponseHead.isKeepAlive` instead of relying on our own test
- Add tests
Happy HTTP/1.0 communication.
> Fix HTTP/1.0 support

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestOptions.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+ManagerTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
- Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
We support the option to ignore `NIOSSLError.uncleanShutdown`. This must also be supported by our new ConnectionPool implementation.
- To not end up with an infinite amount of properties on `HTTPExecutableRequest`, a new `RequestOptions` struct was started, that can be used to set request specific options.
- Added support for `ignoreUncleanSSLShutdown` in the HTTPRequestStateMachine and the HTTP1ConnectionStateMachine. In http/2 `ignoreUncleanSSLShutdown` is always off.
> Ignore unclean ssl shutdown errors

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
Just a reorder within the `HTTPConnectionPool.swift` file. We have an internal type that doesn't need to be in the top of the file. 
Improved readability by moving less important stuff down.
> [HTTPConnectionPool] Move Connections down in the file

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
We have a race between some actions created in the state machine under the `stateLock` and their implementation in the `HTTPConnectionPool`. 
- `_idleTimer` and `_backoffTimer` are protected by `stateLock`
- Added a new `struct Actions` that splits up actions from the state machine into actions that need to be executed inside the `stateLock` and outside in `stateLock`
No more races in timer scheduling.
> [HTTPConnectionPool] Fix timer action races

- docker/docker-compose.2004.55.yaml
motivation: 5.5 release is available
changes: update docker CI setup to use the release version of 5.5
> Use release version of 5.5 in CI

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
If the allocator puts a request at the same address where another request has lived before and we ran into a timer race before, we run into an assertion. This can be seen in test runs here:
https://ci.swiftserver.group/job/async-http-client-swift55-prb/137/console
- Remove `timerLock` from `HTTPConnectionPool`
- No more race conditions. One lock is easier than two.
> [HTTPConnectionPool] Fix request timer scheduling

- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
In #427 we want to switch the implementation over to our new `HTTPConnectionPool`. When we do this, we want to remove the possibility to access the underlying channel. For this reason we need to remove a number of tests from `HTTPClientInternalTests`. As @weissi pointed out, we should at least still integration test downstream backpressure.
This pr replicates the behavior from `HTTPClientInternalTests.testUploadStreamingBackpressure` directly on the `HTTP1Connection`.
- Move and adjust test from `HTTPClientInternalTests.testUploadStreamingBackpressure`
- Rename the test to `testDownloadStreamingBackpressure` since we only test incoming bytes backpressure.
An integration backpressure test, that survives #427.
> [HTTP1Connection] Add download streaming backpressure test

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
> [HTTPClient.Configuration] Make connection pool size configurable

- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
If a `RequestBag` was consuming received http body parts in its `HTTPClientResponseDelegate` in the `didReceiveBodyPart` and received a `succeedRequest`, the `didFinishRequest` was called before the `didReceiveBodyPart` future was resolved.
- Call `didFinishRequest` only once the `didReceiveBodyPart` future was succeeded.
- Fixes test failure that surfaced here: https://ci.swiftserver.group/job/async-http-client-swift55-prb/154/console
> [RequestBag] Fix consumption error in state machine

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
If we currently receive a `101 Switching Protocols` response, we trigger a network reachable crash.
- Handle `101 Switching Protocols` gracefully
> [HTTP1Connection] Handle 101 Switching Protocols

- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
After #427, we now want to make sure, we can eventually remove now unused code. Some tests depend on `TaskHandler`, that actually test other functionality. Work that needs to be merged before #443.
- Replicate four test that depended on `TaskHandler`
- Code can be removed, but tests continue to test.
> Replace tests that depend on `TaskHandler`

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+Backoff.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
We want to use the same backoff algorithm for HTTP1 and HTTP2.
Make `calculateBackoff(failedAttempt:)` a static method on `HTTPConnectionPool` so it can be used in the `HTTP2StateMachine` in the future.
> prepare `calculateBackoff(failedAttempt:)` to be used in `HTTP2StateMachine`

- README.md
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+ManagerTests.swift
- Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
- Tests/AsyncHTTPClientTests/Mocks/MockRequestQueuer.swift
- scripts/soundness.sh
We do not want to accidentally `import NIO` and instead only import `NIOCore`, `NIOPosix` or `NIOEmbedded`.
- replace `import NIO` with corresponding fine-grained import
- add soundness check ([borrowed from `swift-nio-http2`](https://github.com/apple/swift-nio-http2/blob/326f7f9a8c8c8402e3691adac04911cac9f9d87f/scripts/soundness.sh#L55-L62)) so this hopefully never slips in again.
> remove umbrella `NIO` imports and add soundness check

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
Renamed generic function `connectionClosed` to specific `http1ConnectionClose`. We should have specific callbacks for http1 and http2.
> [HTTPConnectionPool] StateMachine has explicit function for HTTP1 connection close

- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine+Demand.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
> [HTTPRequestStateMachine] Allow channelReadComplete at any time

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest.swift
When we lease a new stream from a connection, we only want to cancel the idle timer if the connection was previously actually idle. 
- all lease method now return if a connection was idle before the lease.
- adjust tests to also check the wasIdle flag
> [HTTP2Connections] Return if connection was idle before lease

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
- we should not crash if we close a stream after we have received a go away event
- rename `AvailableConnectionContext` to `EstablishedConnectionContext` to better communicate that the connection might actually not be available and already in the draining state
- add `connectionID` property to `EstablishedConnectionContext` because we might need to schedule an idle timeout if the connection is idle and we do not execute any new requests
- only lease streams if `count` is great then or equal to one
- add variouse tests to verify correct handling of go away events
> [HTTP2StateMachine] test and fix HTTP2 go away

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
To support HTTP/2 we need to integrate the `HTTP2StateMachine` into the new connection pool.
- introduce a new `http2` state case in `HTTPConnectionPool.StateMachine`
- forwards HTTP/1 and HTTP/2 state machine calls to the HTTP2 machine if we are currently in http2 state.
- Fixed a bug in http2 backoff connection creation (created to many connections) 
- Fixed a bug in http2 to http1 migration (returned boolean in `removeAll(_:)` was the inverse of what we actually wanted) which resulted in duplicated connections and lost connections.
Note that we should never hit the `HTTP2StateMachine` or be in the `http2` state because HTTP/2 is still disabled.
- add tests for bug fixes
- add integration tests for `HTTPConnectionPool.StateMachine`
> [HTTP2] integrate `HTTP2StateMachine` into `HTTPConnectionPool.StateMachine`

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
We want to be able to write HTTP/2 integration test for `HTTPClient` and need an option to enable HTTP/2 support without making it available to our adopters yet.
- add internal `HTTP2` Configuration to `HTTPClient.Configuration` and disable it by default
> [HTTP2] Internal `HTTPVersion` configuration

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
Follow up PR for #462 to improve performance as proposed in https://github.com/swift-server/async-http-client/pull/462#discussion_r740921074
This also fixes a bug where we would not create a new connection after a backoff timer fires if we have other connections backing off. (in `hasAnyStartingOrActiveConnectionAnd` we also returned true if a connection is in the backing off state)
> [HTTP2] Improve performance for backoff timer

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
We want to start writing HTTP/2 integration tests
- `HTTP2Connection` now forwards the initial `maxConccurentStreams` settings
- `HTTP2Connection` events are forwarded to `HTTPConnectionPool.StateMachine`
- HTTP/2 events are logged
> [HTTP2] Forward HTTP/2 events to `StateMachine`

- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
SwiftNIO supports informational responses since https://github.com/apple/swift-nio/pull/1984. However this has broken an overly specific test case in AHC.
- Modify test case `HTTP1ConnectionTests.testConnectionDoesntCrashAfterConnectionCloseAndEarlyHints` to support both behaviors
Tests run with NIO main branch.
> Allow NIO HTTPDecoder to correctly support informational responses

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
This PR does two things:
- makes it possible to enabling and disabling HTTP/2 by making `HTTPVersion` public
- set `HTTPVersion` to `.automatic` by default
HTTP/2 will then be used if we connect to a server with HTTPS and the server supports HTTP/2, otherwise we will continue to use HTTP/1.
A user will still be able to disable HTTP/2 if they want to by setting `HTTPVersion` to `.http1Only` on `HTTPClient.Configuration` e.g.:
```
var configuration = HTTPClient.Configuration()
configuration.httpVersion = .http1Only
let client = HTTPClient(
eventLoopGroupProvider: .createNew,
configuration: configuration
)
```
> [HTTP2] Make HTTPVersion public and set to .automatic by default

- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
Binding to all available interface may result in a firewall popup on macOS. We don't want that for our automated tests.
Only bind to the local loopback adapter instead of all interfaces.
> bind to loopback only

- README.md
and add usage guide on how to disable it. 
Also includes one typo fix.
> [HTTP2] State in README that we support HTTP/2

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/Utils.swift
Generally we want to inform users that they need to shutdown their HTTPClient. Until `1.6.0` we did this with an assert in HTTPClient's deinit. With `1.6.0` this behavior was raised to a precondition. This could lead to users to discover suddenly crashes in production, where they have seen none before.
- This pr reverts the current behavior back to something pre `1.6.0`
- HTTPClient doesn't crash in production anymore.
> Only crash in debug mode, if HTTPClient was not shutdown

- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestFramingMetadata.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
The distinction between no request body (`.none`) and a request body of size `0` (`.fixedSize(0)`) is unnecessary and we explicitly have code to ignore this:
https://github.com/swift-server/async-http-client/blob/ec2e080d7011a81bd67f10bf41efe6104d7799d6/Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift#L668-L674
We can therefore just remove it.
- replace `.none` with `.fixedSize(0)`
- remove `.none` from the definition of `RequestFramingMetadata.Body`
> Remove redundant `RequestFramingMetadata.Body.none` case

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
On the swift-server slack a crash was reported:
```bash
2021-11-19T04:19:37.87233336Z 0x55a5a551c262, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66
2021-11-19T04:19:37.872355121Z 0x7f702ab0d3bf
2021-11-19T04:19:37.872771454Z 0x55a5a53cdda6, Swift runtime failure: precondition failure at .build/checkouts/async-http-client/Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift:0
2021-11-19T04:19:37.872787184Z 0x55a5a53cdda6, generic specialization <Swift.Array<AsyncHTTPClient.HTTPConnectionPool.(HTTP2ConnectionState in _06AB5E1F2E49650D236C760F038E3F99)>> of (extension in Swift):Swift.Collection.firstIndex(where: (A.Element) …
```
> Crash fix: HTTP2Connections emit events after the pool has closed them.

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest.swift
We forgot to update the `overflowIndex` during migration from HTTP1 to HTTP2. The added test case would crash without the fix.
> Fix bug in migration from HTTP1 to HTTP2 and back to HTTP1

- Sources/AsyncHTTPClient/RequestBag.swift
- Sources/AsyncHTTPClient/Utils.swift
These 2 Foundation imports are not required. 🧹
> Remove a couple of unnecessary imports

- Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
We want to reuse request validation in the upcoming async/await implementation. During refactoring we noticed some inconsistency in the current implementation on how user defined `Transport-Encoding` and `Content-Length` headers are processed. We concluded that a user should not be allowed to set `Transport-Encoding` or `Content-Length` headers themselves. A user can only communicate its intend through the `body` property on a request. We infer the correct and most optimal `Transport-Encoding` or `Content-Length` header for them.
- `Transport-Encoding` and `Content-Length` or no longer validated and always removed or replaced
- rename `validate` to `validateAndSetTransportFraming` because it does not only validate but also mutate the `HTTPHeaders` to include the correct headers for the …
> Always overwrite `Transport-Encoding` and `Content-Length`

- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
While working on the WebURL port, I noticed that there seemed to be no tests at all covering IPv6.
These are just 2 very simple ones, copies of `testGetHttpsWithIP` and `testGetHTTPSWorksOnMTELGWithIP` which use IPv6 rather than IPv4. It would be good to add more (in particular, I think it would be worth testing that the proxy's CONNECT request-target is properly formatted, but I'm not that familiar with the project so I'm unsure how to write proxy tests).
> [Tests] Add some basic IPv6 tests

- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
If we detect that a user tries to write more bytes as initially specified, we fail the request with a `HTTPClientError. bodyLengthMissmatch`. However, we forgot to update our internal state that the request is failed. One way this manifests is that subsequent errors are also propagated through the stack but should be silently ignored because the request is already failed.
In addition, two compound cases in the switch statement inside of `errorHappened(_:)` had a where clause which did only apply to the last case but should have applied to each compound cases. This affects the `bodyLengthMissmatch` error handling but also all error handling because errors were sometimes treated as `NIOSSLError.uncleanShutdown` even if they were something completely different.
- set state to failed if we …
> Fix `bodyLengthMissmatch` error handling

- .swiftformat
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- docker/Dockerfile
Our current swiftformat version does not support async/await. Since we want to add support for async/await we must update swiftformat or disable it. I tried my very best to keep the number of changes as small as possible. I assume we want to stick with the new 0.48.8 for some time.
- Update swiftformat to 0.48.8
We can land async/await code.
> Update swiftformat to 0.48.8

- docker/docker-compose.yaml
I locally use parallel and randomised testing in Xcode since two months and did not yet encounter any flaky tests. I therefore think we can run tests in parallel on CI as well.
add `--parallel` to `swift test` invocation
> Run tests in parallel on CI

- Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
- Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
fixes #497 
Bind to a port a random free port defined by the operating system instead of using 1080
> Fix flaky tests in `HTTPClientSOCKSTests`

- NOTICE.txt
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
We want to add async/await tests soon but the Linux implementation of XCTest doesn't have async-await support in Swift 5.5. In addition, our `generate_linux_tests.rb` script does not like async/await functions either. We therefore need a workaround to still be to test async/await code.
- add `XCTAsyncTest` and `XCTAssertThrowsError` from https://raw.githubusercontent.com/grpc/grpc-swift/1.4.1-async-await/Tests/GRPCTests/AsyncAwaitSupport/XCTest%2BAsyncAwait.swift
- add NOTICE.txt and list at least SwiftNIO and gRPC
> Add `XCTAsyncTest` and `XCTAssertThrowsError` from gRPC Swift

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
This is currently split across 4 functions (well, 3 functions and an initialiser). It's much easier to understand how AHC understands these URL formats if it happens in a single function (especially since schemes like `http+unix` are not standardised).
Additionally, this rejects empty HTTP hostnames, as they are invalid per the spec, and empty socket paths, since they are meaningless.
> Refactor URL component extraction

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
In HTTPClient we often wrap `XCTAssertEqual` in a `XCTAssertNoThrow`. This isn't actually needed (anymore).
- Remove unused `XCTAssertNoThrow`s
> [Tests] Remove XCTAssertNoThrow that wraps XCTAssertEqual

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/ChannelHandler/HTTP1ProxyConnectHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionTarget.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
I added this as part of the WebURL port, because it can provide specific host kinds and doesn't need to re-parse the hostname, but I think it is generally a useful thing to model.
Currently, `ConnectionPool.Key` stores a `host`, `port`, and `socketPath` string, even though only one of (host + port) and (socketPath) can be populated. This lends itself well to an enum. Additionally, we can extract what kind of host we're dealing with, so we don't need to re-parse the hostname later.
One thing I'd like comments on is whether this should perhaps be moved up to `Request`. This would also allows us to stop pretending that unix domain sockets have ports. As I see it, this should really be `Request`'s business; a part of how it extracts information from the URL should be parsing the hostname …
> Introduce a `ConnectionTarget` enum

- Package.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
We should have http/2 integration tests for requests where we don't know the request size upfront.
- Depend on swift-nio-http2 1.19.0
- Adds 2 integration tests.
Better test coverage for http/2.
> Add HTTP/2 stream integration tests

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/DeconstructedURL.swift
- Sources/AsyncHTTPClient/Endpoint.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/Scheme.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
We want to reuse our URL parsing, validation and deconstruction logic for the upcoming new `HTTPClientRequest` from the async/await proposal.
- Introduce a new `DeconstructedURL` struct which hold a `scheme`, `connectionTarget` and `uri`.
- Introduce a new `DeconstructedURL.Scheme` enum which replaced the previous `String` in `HTTPClient.Request` and `ConnectionPool.Scheme` enum
- move `deconstructURL` logic to an initialiser of  `DeconstructedURL`
- use `DeconstructedURL` instead of separate `scheme`, `connectionTarget`, and `uri` properties in `HTTPClient.Request`
- remove `HTTPClient.Request.Kind` because it is almost a replica of the `DeconstructedURL.Scheme` enum where the only difference is that `http` and `https` are represented as one case called `host`. As we now represent …
> Refactor `deconstructURL ` and `scheme` parsing

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionTarget.swift
- Sources/AsyncHTTPClient/DeconstructedURL.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
Before we can execute a `HTTPClientRequest` we need do a couple of validation and transformation steps which can fail. 
The result of the preparation is now encapsulated in a separate object called `HTTPClientRequest.Prepared`.
> Add HTTPClientReuqest.Prepared

- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/Mocks/MockRequestExecutor.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
To land the support for async/await, we need test utilities. We already have a `MockRequestExecutor`. Let's improve this to better handle on and off request processing.
- Move `MockRequestExecutor` into its own file
- Add blocking APIs to `MockRequestExecutor` when called from another thread
> Improve test utils for running request

- Tests/AsyncHTTPClientTests/Mocks/MockRequestExecutor.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Our actual HTTPRequestExecutors send out a HTTPRequest as soon as they see it and they call `willExecuteRequest` and `requestHeadSent` in very fast succession on the HTTPExecutableRequest. We should have the same behavior in tests.
- Call `requestHeadSent` from `MockRequestExecutor.runRequest`
- Tests that use `MockRequestExecutor` call `runRequest` on it first
Cleaner, more life like tests
> MockRequestExecutor calls `requestHeadSent`

- Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
This PR adds an AsyncWriter that we can be used to test our new async upload streaming API.
- Adds an AsyncWriter to test utils
We will be able to test async upload streaming API in #518.
> Add an AsyncWriter

- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
Currently that test is flaky because of an assertion, we do that doesn't add any value to the test itself.
- Remove unneeded/sometimes failing assertion
- Shutdown the server
Should fix #468.
> Fix flaky test: testConnectionClosesAfterTheRequestWithoutHavingSentAnCloseHeader

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RedirectState.swift
- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
We want to reuse the current redirect logic, which was mainly located inside the `RedirectHandler`, for the upcoming async/await implementation.
- move `HTTPClient.Request.RedirectState` to the top level and a separate file
- refactor redirect logic from `RedirectHandler` into methods on `HTTPHeaders` and methods on `RedirectState`
- use the refactored methods in `RedirectHandler`
> Refactor redirect logic to be reusable for async/await

- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
Otherwise it fails to compile with Xcode 13.1.
Xcode 13.2 seems fine without but this is probably a regression in the swift compiler because the @available anotations are actally needed.
> Add missing @available anotations

- Package.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
NIO gained a new method on `EventLoopGroup` called `.any()` to get the current `EventLoop` if possible. We should use this method to selected the requests preferred `EventLoop` when the user didn't explicitly set a required `EventLoop`. This should improve performance because we increase the chance that we do not need to hop between `EventLoops` to send and receive data.
> Use the current `EventLoop` as the requests preferred `EventLoop`

- Sources/AsyncHTTPClient/HTTPClient.swift
Reduce unnecessary thread switches by using the current `EventLoop` if possible.
> Reduce unnecessary thread switches

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
We forgot to schedule a timeout timer for the user defined deadline and just use it as a connection timeout.
> Respect deadline on new HTTPClient.execute for async/await 

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
Calling `HTTPClient.shutdown()` may never return if connections are still starting and one new established connection results in a state migration (i.e. from HTTP1 to HTTP2 or vice versa). We forgot to migrate the shutdown state. This could result in a large delay until `.shutdown()` returns because we wait until connections are closed because of idle timeout. Worse, it could also never return if more requests are queued because the connections would not be idle and therefore not close itself.
- Mirgrate shutdown state too
- add tests for this specific case
> Fix HTTP1 to HTTP2 migration while shutdown is in progress

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
With Xcode 13.2, and therefore Swift 5.5.2, Swift Concurrency is supported on older Apple OSs. async/await support will no longer be available on Swift before `5.5.2` but this isn't a breaking change because we have not yet made anything of it public.
- replace all `#if compiler(>=5.5) && canImport(_Concurrency)` with `#if compiler(>=5.5.2) && canImport(_Concurrency)`
- replace all `available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)` with `available(macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)`
> Make async/await available on older Apple Platforms

- Sources/AsyncHTTPClient/FoundationExtensions.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
I don't think there is a need for this specific API to use Foundation.Data -- we can broaden it to all RandomAccessCollections . RAC seems like the most appropriate constraint given the up-front `count` calculation.
This removes a Foundation dependency, and should be source-compatible.
> Make Body.data generic

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestValidation.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/RequestValidationTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- add nescary @inlinable/@usableFromInlinable for generic `HTTPClientReuqest.Body` builder metods.
- rename `HTTPClientReuqest.Body.byteBuffer(_:)` to `HTTPClientReuqest.Body.bytes(_:)` to be more in line with the other overloads
- add a new type called `HTTPClientReuqest.Body.Length` instead of `Int?` to specify the length of a body if we can't infer the length
- move `length` parameter to the end
> Prepare async/await API for public release

- NOTICE.txt
- Sources/AsyncHTTPClient/Base64.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
Uses @fabianfett's base64 implementation rather than Foundation. Apparently it's faster, and it avoids copying the string to a Foundation.Data object before encoding.
Single-file version copied from https://github.com/apple/swift-nio/blob/main/Sources/NIOWebSocket/Base64.swift
I disabled swiftformat on the file so that, other than the copyright header and swiftformat comment, it remains identical to the version in NIO. Alternatively, we could add a package dependency rather than copying the file. Up to you guys.
With this and #534, the only remaining Foundation dependencies will be `URL`, and the couple of convenience APIs in the `FoundationExtensions` file. If they're both accepted, I can go through and replace all occurrences of `import Foundation` with `import struct Foundation.URL` in …
> Used vendored base64 encoding implementation rather than Foundation.Data

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
If we hit a `precondition` because of an invalid state, we should print the state to make debugging easier.
> Print invalid state, if hitting precondition

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
We may have a race condition between scheduling a request on an http/1.1 connection and the connection being closed.
- Fail request that is scheduled on a closed connection
We don't crash anymore.
> Fix race between connection close and scheduling new request

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
Cherry pick #545 into `http-client-1.8`.
> Cherry pick: Print invalid state, if hitting precondition (#545)

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1.1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
Cherry pick #546 into http-client-1.8.
> Cherry pick: Fix race between connection close and scheduling new request (#546)

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
This PR makes the `logger` parameter of `execute` optional and will use a no-op logger if nil.
In addition, it also adds a new `execute` method which takes a `timeout` instead of a `deadline`.
> Disable logging by default and add timeout API

- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
`#if compiler` and `#available` probably didn't get correctly updated after some merge conflict.
Couldn't find any other reference for `compiler(>=5.5)` in the code base.
> Fix compilation of tests for Swift 5.5.0/5.5.1

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- scripts/soundness.sh
Allows to shutdown a `HTTPClient` in an async context without blocking or using the callback version of shutdown.
> Add `async` shutdown method to `HTTPClient`

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
It's finally time to release the new async/await APIs 🥳
PR with example and updated `README.md` will follow.
> Make new async/await API public

- README.md
We want to highlight the new async/await API in the README. 
- add new examples for async/await but keeps old examples for SwiftNIOs `EventLoopFuture`s
- change URL used in examples from swift.org to apple.com because swift.org doesn't respect that we don't support compression by default which results in gibberish output if examples are run by users.
- increase recommended Xcode Version to 13.2 and Swift Version to 5.5.2
- increase recommend AsyncHTTPClient version to `1.9.0`
> Update README.md for async/await

- Examples/GetHTML/GetHTML.swift
- Examples/GetJSON/GetJSON.swift
- Examples/Package.swift
- Examples/README.md
- Examples/StreamingByteCounter/StreamingByteCounter.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
This PR adds examples which make use of the new async/await APIs. Sadly, async/await is not supported in top level code [(but there is a pitch)](https://forums.swift.org/t/concurrency-in-top-level-code/55001). Just spinning up a task is not enough, we also need to wait for its completion. The new `@main` attribute already supports async/await and automatically waits for completion but we need to mark the target as an `executableTarget`. `executableTargets` were introduced in Swift 5.4 and we therefore need swift-tools-version 5.4. As we still support Swift 5.2 and Swift 5.3 we sadly need to create separate Package.swift files. 
Alternatively, we could also use a semaphore to wait until completion. But as this is an example, we should be a role model.
Note: this PR requires the newest …
> Add async/await examples

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
If a already cancelled request is scheduled on an existing HTTP/2 connection we currently run into a crash. This only happens if the request is scheduled on the same EventLoop as the HTTP/2 connection. 
- Make the `HTTPRequestStateMachine` resilient to failures before request start.
- A crash less.
> Crash fix: HTTP2 can handle requests are cancelled

- Examples/Package.swift
- Package.swift
`swift-nio` has defined a new method `collect(upTo:into:)` on `AsyncSequence` which we use in our examples.
> Use newest `swift-nio` version

- Sources/AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift
Motivation:
SSLProtocol's tlsProtocol* members are deprecated but we need them in compatibility code (breaks SemVer otherwise).
Modification:
Annotate the legacy function as such.
Result:
Fewer warnings.
> SSLProtocol tls* deprecations

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
AHC can currently not deal with direct failures when writing requests.
- Make `HTTP2ClientRequestHandler` resilient to failing writes
Less crashes in AHC HTTP/2.
> Crash fix: HTTP2ClientRequestHandler can deal with failing writes

- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Motivation
The RequestBag intermediates between two different threads. This means
it can get requests that were reasonable when they were made but have
been superseded with newer information since then. These generally have
to be tolerated.
Unfortunately if we received a request to resume the request body stream
_after_ the need for that stream has been invalidated, we could hit a
crash. That's unnecessary, and we should tolerate it better.
Modifications
Tolerated receiving requests to resume body streaming in the finished
state.
Result
Fewer crashes
Fixes #576
> Tolerate the request stream being started after .finished

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
Same fix for HTTP/1 that landed for HTTP/2 in #558.
`HTTP1ClientChannelHandler` currently does not tolerate immediate write errors.
Make `HTTP1ClientChannelHandler` resilient to failing writes.
Less crashes in AHC HTTP/1.
> [HTTP1] Tolerate immediate write errors

- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Currently, we don’t consume the response body of redirect responses. Because of this requests, that receive a redirect response with response body, may hang indefinitely.
- Consume redirect response body if less than 3kb
- Cancel redirect response if larger than 3kb
Redirect responses are consumed. Fixes #574
> [Redirect] Allow redirect response to have body

- Sources/AsyncHTTPClient/HTTPClient.swift
This adds a shortDescription property to HTTPClientError which provides a short
description of the error without associated values.
This is useful for e.g. metric labels which should not contain dynamic, potentially unbounded, associated values.
> Add HTTPClientError shortDescription property

- .swiftformat
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
We observed a test failure on our CI:
```
/async-http-client/Tests/AsyncHTTPClientTests/HTTPClientTests.swift: error: HTTPClientTests.testResponseDelayGet : XCTAssertGreaterThan failed: ("1.9851820468902588") is not greater than ("2.0") -
Test Case 'HTTPClientTests.testResponseDelayGet' failed (1.989 seconds)
```
I could not reproduce the failure myself but giving this a bit more leeway does not hurt. To measure the time difference, we now use `NIODeadline` which internally uses nanoseconds since boot to measure the time instead of `Date`. `Date` uses the system time which may change during execution due to time sync with a time server and is therefore not best suited to measure elapsed time.
Immune to system time sync and slightly higher tolerance agains inaccurate timer implementations.
> Fix flaky `HTTPClientTests.testResponseDelayGet()` test

- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPRequestStateMachineTests.swift
- Tests/AsyncHTTPClientTests/Mocks/MockRequestExecutor.swift
Right now, we call `didSendRequestPart` after passing the write to the executor. However, this does not mean that the write hit the socket. To implement proper backpressure using the delegate, we should only call this method once the write was successful.
Pass a promise to the actual channel write and only call the delegate once that promise succeeds.
The delegate method `didSendRequestPart` is only called after the write was successful.
> Call `didSendRequestPart` at the right time

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/NIOTransportServices/NWWaitingHandler.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
Motivation
Currently error reporting with NIO Transport Services is often sub-par.
This occurs because the Network.framework connections may enter the
waiting state until the network connectivity state changes. We were not
watching for the user event that contains the error in that state, so if
we timed out in that state we'd just give a generic timeout error,
instead of telling the user anything more detailed.
Additionally, several of our tests assume that failure will be fast, but
in NIO Transport Services we will enter that .waiting state. This is
reasonable, as changed network connections may make a connection that
was not succeeding suddenly viable. However, it's inconvenient for
testing, where we're mostly interested in confirming that the error path
works as expected.
Modifications …
> Improve errors and testing using NIOTS

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
It's totally acceptable for a HTTP server to respond before a request
upload has completed. If the response is an error, we should abort the
upload (and we do), but if the response is a 2xx we should probably just
finish the upload.
In this case it turns out we'll actually hit a crash when we attempt to
deliver an empty body message. This is no good!
Once that bug was fixed it revealed another: while we'd attempted to
account for this case, we hadn't tested it, and so it turns out that
shutdown would hang. As a result, I've also cleaned that up.
Modifications
- Tolerate empty circular buffers of bytes when streaming an upload.
- Notify the connection that the task is complete when we're done.
Result
Fewer crashes and hangs.
Resolves #562
> Fix crash when receiving 2xx response before stream is complete.

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
We have observed some test failures on our CI where `198.51.100.254` accepts connection but it shouldn't.
Luckily, this happens only on macOS and we can workaround this by creating a local TCP server with a backlog of `1`.
This server will only send a `SYN/ACK` back to the first connection as it doesn't actually accept the connection. Further connection attempts will not see a `SYN/ACK`. We can use this behaviour to test a connection timeout on macOS.
The backlog behaviour on Linux can not be used to simulate a non-reachable server. Linux sends a `SYN/ACK` back even if the `backlog` queue is full as it has two queues. The second queue is not limit by `ChannelOptions.backlog` but by `/proc/sys/net/ipv4/tcp_max_syn_backlog`. We will therefore fallback to `198.51.100.254` on Linux.
> Use a local TCP server that doesn’t accept connections on macOS for `testConnectTimeout()`

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
When users stream their bodies they may still want to send Connection:
close headers and terminate the connection early. This should work
properly.
Unfortunately it became clear that we didn't correctly pass the
information that the connection needed to be closed. As a result, we'd
inappropriately re-use the connection, potentially causing unnecessary
HTTP errors.
Modifications
Signal whether the connection needs to be closed when the final
connection action is to send .end.
Results
We behave better with streaming uploads.
> Correctly handle Connection: close with streaming

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
Motivation
If we receive an early HTTP response, the last action on a HTTP/1.1
connection is to send the .end message. While we had an error handling
path in the code, it wasn't tested, and when executed it would end up
leaking the connection by failing to close it _or_ return it to the
pool.
This patch fixes the issue by appropriately terminating the connection
and adding a test.
Modifications
Add a test
Terminate the connection if sendEnd fails
Result
Fewer connection leaks
> Correctly close the connection if sendEnd fails

- Package.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+StateTestUtils.swift
`NIOAtomics` was deprecated in https://github.com/apple/swift-nio/pull/2204 in favor of `swift-atomics` https://github.com/apple/swift-atomics
> Use `swift-atomics` instead of `NIOAtomics`

- Sources/AsyncHTTPClient/HTTPClient.swift
Motivation
Warnings aren't great, and NIOAtomic is deprecated.
Modifications
Replace the last use of NIOAtomic with ManagedAtomic.
Result
Fewer warnings
Fixes #606
> Remove the last remaining NIOAtomic

- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
If the deadline is exceeded and the connection state machine fails the request with an error, we forgot to transition to the finished state in the `RequestBag`. A symptom of this is that a request could afterwards still be canceled from user code and it would trigger a second call to the delegates `didRecieveError` method.
- transition to the finished state
- add a test which fails without the change above
`didReceiveError` can't be called twice
> Don’t call `didReceiveError` twice if deadline is exceeded and request is canceled afterwards

- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
Port changes over from https://github.com/swift-server/async-http-client/pull/601 to the async/await API
> Report last connection error if request deadline is exceeded with async/await API

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Fixes https://github.com/swift-server/async-http-client/issues/537
> Support transparent decompression with HTTP/2

- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
When receiving certain patterns of response body parts, we can end up
recursing almost indefinitely to deliver them to the application. This
can lead to crashes, so we might politely describe it as "sub-optimal".
Modifications
Keep track of our stack depth and avoid creating too many stack frames.
Added some unit tests.
Result
We no longer explode when handling bodies with lots of tiny parts.
> Limit max recursion depth delivering body parts

- Package@swift-5.4.swift
- Package@swift-5.5.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Sources/AsyncHTTPClient/Docs.docc/index.md
- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/NIOTransportServices/NWErrorHandler.swift
- Sources/AsyncHTTPClient/Utils.swift
- docker/docker-compose.1804.54.yaml
- docker/docker-compose.2004.55.yaml
- docker/docker-compose.yaml
- scripts/soundness.sh
Motivation
Documentation is nice, and we can help support users by providing useful
clear docs.
Modifications
Add Docc to 5.6 and later builds
Make sure symbol references work
Add overview docs
Result
Nice rendering docs
> Use Docc for documentation

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
Motivation
We should apply the connect timeout to the complete set of connection
attempts, rather than the request deadline. This allows users
fine-grained control over how long we attempt to connect for. This is
also the behaviour of our old-school interface.
Modifications
- Changed the connect deadline calculation for async/await to match that
of the future-based code.
- Added a connect timeout test.
Result
Connect timeouts are properly handled
> Accurately apply the connect timeout in async code

- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
We might still get pending buffers if the user has canceled the request because they might already be enqueued to be delivered. We therefore need to tolerate buffers after we are in the error state.
Fixes https://github.com/swift-server/async-http-client/issues/612
> Tollerate more data after request body is cancelled

- Sources/AsyncHTTPClient/HTTPClient.swift
`ProcessInfo` is a Foundation API, so this broke the Foundationless build
> Use NIOCore.System.coreCount for the fileIO thread pool

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests+XCTest.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
`AsyncSequence.makeAsyncIterator()` was only called once during the creation of `HTTPClientRequest.Body` and would have been shared if an `HTTPClientRequest` is executed a second time. 
- call `AsyncSequence.makeAsyncIterator()` for each invocation of `HTTPClient.execute`
- create a test which would previously fail
We no longer share the `AsyncIterator` between different request executions. If the given `AsyncSequence` actually supports multiple iterators, and therefore can be correctly used by multiple request executions, depends on the concrete type though.
> Allow `HTTPClientRequest` to be executed multiple times if `body` is an `AsyncSequence`

- Package.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/SSLContextCache.swift
- Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
SwiftNIO 2.42.0 has deprecated Lock and replaced it with a new NIOLock. This commit removes all uses of Lock and replaces them with NIOLock. Further now we must require SwiftNIO 2.42.0
> Replace Lock with NIOLock

- Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
If we want to make progress on a 2/3-tier design, we need to take proxy settings into account for pool keying.
- Make `HTTPClient.Configuration.Proxy` hashable
> Add `Hashable` conformance to `HTTPClient.Configuration.Proxy`

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Tests/AsyncHTTPClientTests/EmbeddedChannel+HTTPConvenience.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
If we introduce a new 2/3 tier design, we have a new configuration object next to `HTTPClient.Configuration`. To prepare the way, we should reduce the areas in which we rely on `HTTPClient.Configuration` directly.
- Depend on only the decompression settings in `HTTP1Connection` and `HTTP2Connection`
- Remove dead/unused code
> Reduce use of `HTTPClient.Configuration` in the Connection objects

- Sources/AsyncHTTPClient/HTTPClient.swift
If we want to make progress on a 2/3-tier design, we need to take the http version settings into account for pool keying.
- Make `HTTPClient.Configuration.HTTPVersion` hashable
> Add `Hashable` conformance to `HTTPClient.Configuration.HTTPVersion`

- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
`RequestBag.consumeMoreBodyData0(resultOfPreviousConsume:)` should be called for errors thrown by the delegate instead of `RequestBag.fail(_:)`.
Test added in the first commit hangs without the second commit which calls the right method.
> Fix request hang if delegate fails promise returned by `didReceiveBodyPart`

- Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/AsyncHTTPClient/HTTPClient+Proxy.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
We now require Swift 5.5.2 which includes `Sendable` so we no longer require the `NIOSendable` workaround.
`NIOSendable` is just a `typealias` of `Sendable` so this is a non source breaking change.
This allows `swift-nio` to eventually deprecate `NIOSendable`.
> Replace `NIOSendable` with `Sendable`

- README.md
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+execute.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClient+shutdown.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/SSLContextCache.swift
- Sources/AsyncHTTPClient/UnsafeTransfer.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
We only support Swift 5.5.2+. 
Remove a lot of our `#if swift(>=5.5)` conditional compilation blocks.
less branching
> Remove `#if compiler(>=5.5)`

- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
This is a trivial struct that should be `Sendable`, as it's a common use case to pass `Progress` values to `@Sendable` closures.
> FileDownloadDelegate: mark `Progress` as `Sendable`

- README.md
AsyncHTTPClient now requires at least Swift 5.5.2. The async/await APIs are therefore available in all supported Swift compiler versions.
Swift Concurrency and HTTP/2 are now also supported for some time now. No need to call out the specific version in the readme. This information can still be found in the release notes if needed.
> Remove obsolete notes in README.md

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
A channel can close unexpectedly if something goes wrong. We may in the meantime have scheduled the connection for graceful shutdown but the connection has not yet seen the message. We need to still accept the shutdown message and just ignore it if we are already closed.
- ignore calls to shutdown if the channel is already closed
- add a test which would previously crash because we have transition from the closed state to the closing state and we hit the deinit precondition
- include the current state in preconditions if we are in the wrong state
We don’t hit the precondition in the deinit in the scenario described above and have more descriptive crashes if something still goes wrong.
> Tolerate shutdown message after channel is closed

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
Previous code assumed that we were always in the running state. We therefore never transition from the shuttingDown to the shutDown state if the last connection in the pool fails.
- don't start new connection and instead correctly shutdown the pool if the last connection failed
- add test which previously failed
HTTPClient is correctly shut down if HTTP2 connections establishment fails while shut down is in progress.
Resolves https://github.com/swift-server/async-http-client/issues/638
> Correctly shutdown `HTTP2ConnectionPool` if connection creation fails.

- Sources/AsyncHTTPClient/ConnectionPool/ChannelHandler/HTTP1ProxyConnectHandler.swift
- Tests/AsyncHTTPClientTests/HTTP1ProxyConnectHandlerTests.swift
I realized that `Host` header is missing which causes `400 Bad Request: missing required Host header`.
I added missing header into `HTTP1ProxyConnectionHandler` and now it works like a charm!
Also added `Host` header check into tests.
> Add `Host` header (#650)

- Sources/AsyncHTTPClient/HTTPHandler.swift
This change was proposed in issue [#389](https://github.com/swift-server/async-http-client/issues/389).
Users writing their own `HttpClientResponseDelegate` implementation
might want to emit log messages to the `task`'s `logger`.
Changed the access level of `Task`'s `logger` property from `internal`
to `public`.
Users can access the `logger` property of a `Task` outside of the
`async-http-client` Package.
> Make Task.logger accessible to delegate implementations outside of Package

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestBag+StateMachine.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/RequestBagTests+XCTest.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Fixes #663.
- We need to drop references to the request body, that we execute in the RequestBag as soon as we can to destroy the reference cycle.
- To make this easier to read I moved the `redirectHandler` into the state enum
- We also don't retain the request in the `ResponseAccumulator` anymore
> Fix Request streaming memory leak

- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Tests/AsyncHTTPClientTests/TransactionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
We simply forgot to set the state to `.failed`.
Added a test which previously crashed.
Fixes #664
> Fix request head continuation misuse

- README.md
- Sources/AsyncHTTPClient/Docs.docc/index.md
- Sources/AsyncHTTPClient/HTTPClient.swift
Motivation
syncShutdown can cause unbounded thread blocking, we shouldn't allow it in concurrent code.
Modification
Mark syncShutdown unavailable from async.
Result
Users are warned if they try to syncShutdown in an async context
> Make syncShutdown unavailable from async

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
We leak `HTTP2StreamChannel`s in long living HTTPClients. The reason for this is that we registered the callback to remove an `HTTP2StreamChannel` from the openStreams set in HTTP2Connection on the HTTP2 connection channel and not on the `HTTP2StreamChannel` itself. (Side note: `self.channel` vs local `var channel` is always crazy dangerous)
- Actual bug fix (remove a `self.`)
- Ensuring that we always close the `HTTP2StreamChannel` when the request has finished
- Add a test for a previous uncovered code path (request receives full response before being done writing)
> Fix HTTP2StreamChannel leak

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
If the channel is closed before flatMap is executed, all ChannelHandler are removed and `TLSEventsHandler` is therefore not present either. We need to tolerate this even though it is very rare.
Testing ideas welcome.
Fixes #670
> Fix crash if connection is closed very early

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2IdleHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2Connections.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP2StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+StateMachine.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2IdleHandlerTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTP2IdleHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1ConnectionsTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP1StateTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2ConnectionsTest.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+HTTP2StateMachineTests.swift
- Tests/AsyncHTTPClientTests/Mocks/MockConnectionPool.swift
Motivation:
Sometimes it can be helpful to limit the number of times a connection
can be used before discarding it. AHC has no such support for this at
the moment.
Modifications:
- Add a `maximumUsesPerConnection` configuration option which defaults
to `nil` (i.e. no limit).
- For HTTP1 we count down uses in the state machine and close the
connection if it hits zero.
- For HTTP2, each use maps to a stream so we count down remaining uses
in the state machine which we combine with max concurrent streams to
limit how many streams are available per connection. We also count
remaining uses in the HTTP2 idle handler: we treat no remaining uses
as receiving a GOAWAY frame and notify the pool which then drains the
streams and replaces the connection.
Result:
Users can control how many times each …
> Add a control to limit connection reuses

- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
If the HTTP response status is not 2xx or the file being downloaded becomes too big, it is desirable to cancel the file download eagerly. This is currently quite hard because the `reportHead` and `reportProgress` closures do not have direct access to the `HTTPClient.Task`.
- Pass `HTTPClient.Task` additionally to `reportHead` and `reportProgress` closures
A file download can now easily be cancelled at any time.
> Pass request `Task` to `FileDownloadDelegate` `reportHead` and `reportProgress` closures

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests+XCTest.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPoolTests.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
A users might want to provide more information why a request got cancelled. For example if we cancel a file download because the response status code is not 2xx, it is desirable to propagate which status code was returned.
- add `Task.fail(_:)` in addition to `Task.cancel()` that takes a custom Error which is used to complete the underlying request promise.
Improved error messages.
> Add support for custom cancellation error

- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
The repo currently won't build for other OS's because the extension doesn't match: https://github.com/swift-server/async-http-client/blob/2588b8cdd4be62f72da849f42ec1d1b25c985937/Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift#L21-L22
> Fix building transaction extension for Apple Platforms

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
A connection and the connection pool may be on different threads and therefore run concurrently. If a connection error happens the connections closes itself and notifies the pool about it. While this is happening the connection pool could already decide to run a new connection on the closing connection. We need to tolerate this happening. We already partially do but only if the connection is fully closed but not currently still closing.
- change all `preconditionFailure`s in `HTTP1ConnectionStateMachine.swift` to `fatalError`s to see the message in release builds
- tolerate `.closing` in addition to `.closed` in `runNewRequest`
- add test which previously crashed
AHC no longer crashes in the race condition described above.
> Tolerate new request after connection error happened

- Sources/AsyncHTTPClient/Base64.swift
This increase the code verification with the right statement including all platforms that use Darwin.
> Replace os() with canImport(Darwin)

- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
There are some usage of the word `Auhorization` and this PR changes to `Authorization`
> Fix auhorization typo

- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
We have observed that `AsyncAwaitEndToEndTests.testImmediateDeadline` can also return a `HTTPClientError.remoteConnectionClosed` in rare circumstances. If closing  happens really fast we might shutdown the pipeline before we fail the request. If the pipeline is closed we may receive a  `.remoteConnectionClosed` which can execute before we push the previous error to the request state machine. We can't change this in the current architecture so we will just tolerate this error in tests as well. 
The `AsyncAwaitEndToEndTests.testDeadline()` is less likely to experience this issue but I have changed it there too just to be safe.
> Fix flaky `AsyncAwaitEndToEndTests.testImmediateDeadline` test

- Tests/AsyncHTTPClientTests/RequestBagTests.swift
We have seen that the `RequestBagTests.testCancelFailsTaskAfterRequestIsSent` can timeout the CI in #698. To better understand where it fails we can add a timeout that will throw with a timeout error and fail the error check below it. This will make will allow us in the future to better analyse the failure and will no longer timeout the CI.
> Add timeout to `RequestBagTests.testCancelFailsTaskAfterRequestIsSent` test

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
URL parsing has changed in macOS Sonoma and associated releases. Our tests were reliant on the old behaviour. The behaviour is controlled by the OS on which the program was linked, which makes it impossible for us to programmatically work out which result we should see.
The affected tests are not actually useful, we don't really care how the URLs parse, so we can safely just remove them.
Modifications
Remove the affected tests.
Result
Tests pass!
> Remove tests relying on OS-dependent behaviour

- Package.swift
- README.md
- Sources/AsyncHTTPClient/Docs.docc/index.md
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInformationalResponsesTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
use https://github.com/apple/swift-nio/pull/2471 and https://github.com/apple/swift-nio-transport-services/pull/180 (once available)
Relevant discussion: https://github.com/apple/swift-nio/issues/2498
> use NIOSingletons EventLoops/NIOThreadPool instead of spawning new

- Package.swift
- Tests/AsyncHTTPClientTests/NWWaitingHandlerTests.swift
**Motivation:**
Closes #589. Since we already have a public initializer for `NIOTSNetworkEvents.WaitingForConnectivity`, we should add unit tests for the handler now that it's straightforward.
I'm here to learn — first patch in `async-http-client`.
**Modifications:**
The tests are in their own file `Tests/NWWaitingHandlerTests.swift`.
> Add unit tests for NWWaitingHandler, closes #589

- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Motivation:
The above test has been seen to fail with port already in use. The test assumes that a port can be bound to twice in a row. It's possible that another process takes the port between the two binds - this can be stopped by binding a second time before stopping the first.
Modifications:
Allow port reuse and reorder the test to bind a second time before releasing the first.
Result:
Test should no longer be flaky.
> testPlatformConnectErrorIsForwardedOnTimeout port reuse

- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestOptions.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
We currently provide an idle read timeout to fail requests that take more than a given amount of time to produce any response data. We were missing its counterpart: to provide a timeout for when no request data is being written either. 
This could happen, for example, when uploading large files: if for whatever reason (e.g. back pressure from the server, etc) the client does not write any bytes, and there is no data being sent from the server either, the connection could be idle and unused, but remain open for longer than necessary. With an idle write timeout, we can avoid this.
Added a new idle write timeout.
Users can now configure an idle write timeout in addition to an idle read timeout.
> Add an idle write timeout

- Sources/AsyncHTTPClient/NIOTransportServices/TLSConfiguration.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientResponseTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/NWWaitingHandlerTests.swift
- Tests/AsyncHTTPClientTests/Transaction+StateMachineTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- Tests/AsyncHTTPClientTests/XCTest+AsyncAwait.swift
Some of the test code was missing availability guards for Apple platforms, resulting in build failures for these platforms, e.g.
```
error: 'AsyncSequence' is only available in iOS 13.0 or newer
```
Add missing availability guards. I've tried to keep them as scoped as possible.
Tests can now build for run on iOS and other Apple platforms.
> Add missing availability guards in tests

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
This PR is a follow-up to https://github.com/swift-server/async-http-client/pull/718. It applies the same modifications done in https://github.com/swift-server/async-http-client/pull/455 to the HTTP2 request handler to avoid a race condition when cancelling idle timers.
A new timer ID for each timer (read and write idle timeouts) has been added to keep track of the current idle timers, just like it's done in the HTTP1 implementation.
No more race conditions when cancelling timers in HTTP2.
> Fix potential race conditions when cancelling read/write idle timers

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
We provide some initialisers for `HTTPClient.Configuration` where users can provide idle timeouts for the connection pools used. However, we don't propagate those values down to the connection pool. This caused bugs in adopters' code.
Propagate the idle timeout down to the connection pool.
The given idle timeout is now actually used.
> Use the given connection pool idle timeout in the HTTPClient.Configuration inits

- Package.swift
https://github.com/swift-server/async-http-client/pull/718 moved to `TransactionBody.makeSequence(backPressureStrategy:finishOnDeinit:delegate:)` (from `TransactionBody.makeSequence(backPressureStrategy:delegate:)`). This change was introduced in `swift-nil`, v2.62.0 - however, the minimum version of NIO for this package was not updated, which can cause some dependency issues for some users.
Update the required min version of `swift-nio` to 2.62.0 (up from 2.58.0).
No more dependency issues.
> Update minimum swift-nio version

- Package.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+Backoff.swift
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/CAsyncHTTPClient/CAsyncHTTPClient.c
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
We would like to make this work for Musl so that we can build fully statically linked binaries that use AsyncHTTPClient.
Define `_GNU_SOURCE` as a compiler argument; doing it in a source file doesn't work properly with modular headers.
Add imports of `Musl` in appropriate places.
`Musl` doesn't have `strptime_l`, so avoid using that.
async-http-client will build for Musl.
> Add support for Musl.

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
The write timeout was being received as a parameter in the config's initialiser, but it wasn't being set on the config struct. Also tests for the write timeout were missing.
- The write timeout value is now set on init.
- There are now tests for the write timeout.
Proper idle write timeouts and tests.
> Fix write timeout not being initialised

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
It was previously (https://github.com/swift-server/async-http-client/pull/705/files#diff-5c6f847a120449cc304f0b6bf128d6815957bc27adb6c8af024809e132210529R3577) accidentally (i assume) moved to a different test, which does not need it 
Async tests need the guard for macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0
> Move availability guard to correct test

- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
This solves https://github.com/swift-server/async-http-client/issues/737
We are currently creating H2 connections using the default NIO settings, but this means we weren't sending `SETTING_ENABLE_PUSH=0`. This caused the server to push streams to the client, which messed up the stream count logic (as we were assuming only the client could create new streams), resulting in a precondition failure when releasing streams.
This PR updates the settings to disable the `enablePush` setting.
> Disable SETTINGS_ENABLE_PUSH HTTP/2 setting

- Examples/GetHTML/GetHTML.swift
- Examples/GetJSON/GetJSON.swift
- Examples/StreamingByteCounter/StreamingByteCounter.swift
The README was updated to use `.singleton` in all the examples as a part of this PR: https://github.com/swift-server/async-http-client/pull/697, but it looks like the files in /Examples were missed.
> Update Examples to use `.singleton`

- Sources/AsyncHTTPClient/Configuration+BrowserLike.swift
This enables the decompressor to decompress files that have been 96% compressed, instead of the previous 90%, when using `HTTPClient.shared`.
See https://github.com/swift-server/async-http-client/issues/739.
I'm also fine with decreasing the ratio to 20, if 25 seems too high.
> Increase decompression limit ratio of `HTTPClient.shared` 10 -> 25

- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientNIOTSTests.swift
Currently, there is no way to instantly return when a connection attempt fails. The connection timeout is always awaited, regardless of the connection error. When used within a service, this behavior makes sense – network conditions may temporarily prevent establishing a connection. However, in a user-interactive environment, it's preferable to fail quickly and display the error to the user.
#625 introduced the property [`retryConnectionEstablishment`](https://github.com/swift-server/async-http-client/blob/0ae99db85b2b9d1e79b362bd31fd1ffe492f7c47/Sources/AsyncHTTPClient/HTTPClient.swift#L1028), which defaults to `true` but can be set to `false` to **not** retry on connection failure. The property was added to speed up unit tests, but would also be suitable for the use-case mentioned …
> Make ConnectionPool's `retryConnectionEstablishment` public

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPRequestStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestBodyLength.swift
- Sources/AsyncHTTPClient/ConnectionPool/RequestFramingMetadata.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/NoBytesSentOverBodyLimitTests.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
- The properties that store the request body length and the cumulative number of bytes sent as part of a request are of type `Int`. 
- On 32-bit devices, when sending requests larger than `Int32.max`, these properties overflow and cause a crash.
- To solve this problem, the properties should use the explicit `Int64` type.
- Changed the type of the `known` field of the `RequestBodyLength` enum to `Int64`.
- Changed the type of `expectedBodyLength` and `sentBodyBytes` in `HTTPRequestStateMachine` to `Int64?` and `Int64` respectively.
- Deprecated the `public var length: Int?` property of `HTTPClient.Body` and backed it with a new property: `contentLength: Int64?`
- Added a new initializer and "overloaded" the `stream` function in `HTTPClient.Body` to work with the new `contentLength` …
> Add support for request body to be larger than 2GB on 32-bit devices

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- When the leading slash is omitted in the `string` argument of a relative `URL` instance constructed from `init(string:relativeTo)`, requests made with this `URL` instance fail. This is because the underlying HTTP parser fails when there is no leading slash in the URI.
- The URI of a `URL` instance is obtained from a computed property `uri` in `HTTPHandler.swift`, which in turn calls the `percentEncodedPath` computed property.
- The `percentEncodedPath` property uses `URLComponents` to extract out the path.
- The `resolvingAgainstBaseURL` argument to the `URLComponents` constructor was modified from `false` to `true` 
- Regardless of whether a user provides or omits a leading slash in the path of a relative `URL`, the `uri` property will always contain a leading slash.
> Fix leading slash issue in relative URL requests

- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
> Avoid using deprecated API in tests

- Sources/AsyncHTTPClient/HTTPHandler.swift
`HTTPClient.Response` is trivially `Sendable`, let's mark it `Sendable`.
> mark HTTPClient.Response Sendable

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+HTTP1Connections.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
When a user wishes to make the connection pool create as many concurrent connections as possible, a natural way to achieve this would be to set `.max` to the `concurrentHTTP1ConnectionsPerHostSoftLimit` property.
```swift
HTTPClient.Configuration().connectionPool = .init(
idleTimeout: .hours(1),
concurrentHTTP1ConnectionsPerHostSoftLimit: .max
)
```
The `concurrentHTTP1ConnectionsPerHostSoftLimit` property is of type `Int`. Setting it to `Int.max` leads to `Int.max` being passed as an argument to `Array`s `.reserveCapacity(_:)` method, causing an OOM issue.
Addresses Github Issue #751 
Capped the argument to `self.connections.reserveCapacity(_:)` to 1024 in `HTTPConnectionPool.HTTP1Connections`
Users can now set the `concurrentHTTP1ConnectionsPerHostSoftLimit` property to `.max` without …
> Fix OOM issue when setting `concurrentHTTP1ConnectionsPerHostSoftLimit` to `Int.max`

- .github/release.yml
Motivation:
Would like to use github to autogenerate release notes.
Modifications:
Bring over configuration consistent with NIO and other popular repos.
Result:
Once labels are synchronised release notes can be generated by github
> Add releases.yml config for github

- Package.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
`NIOTooManyBytesError` now requires the `maxBytes` in its initializer.
> Fix NIO deprecations after update to `2.71.0`

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
If the channel's writability changed to false just before we finished a request, we currently run into a precondition.
- Remove the precondition and handle the case appropiatly
A crash less.
> Fix crash when writablity becomes false and races against finishing the http request

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
The Darwin module is slowly being split up, and as it gets further along, it will stop importing some of the split-out modules like the one for locale.h that provides newlocale() and other locale API. However, there's a wrinkle that on platforms with xlocale, it's xlocale.h that provides most of the POSIX locale.h functions and not locale.h, so prefer the xlocale module when available.
> Explicitly import locale modules

- Package.swift
This PR adds .git extensions to the Swift Package Manager dependencies that didn't include them. For me, this resolves issues that I have had with an error produced by Xcode when updating to the latest package versions if I'm editing the project which depends on AHC in an Xcode Workspace. 
The complete error is: `github.com: https://github.com/apple/swift-algorithms: The repository could not be found. Make sure a valid repository exists at the specified location and try again.`
Based on conversations in the Vapor Discord server, adding these extensions "shouldn't" make a difference to the dependency resolution done by swift package manager, however adding them resolves the error. 🤷
> add .git extensions to dependency URLs

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Multipath TCP (MPTCP) is a TCP extension allowing to enhance the reliability of the network by using multiple interfaces. This extension provides a seamless handover between interfaces in case of deterioration of the connection on the original one. In the context of iOS and Mac OS X, it could be really interesting to leverage the capabilities of MPTCP as they could benefit from their multiple interfaces (ethernet + Wi-fi for Mac OS X, Wi-fi + cellular for iOS).
This contribution introduces patches to HTTPClient.Configuration and establishment of the Bootstraps. A supplementary field "enableMultipath" was added to the configuration, allowing to request the use of MPTCP. This flag is then used when creating the channels to configure the client.
Note that in the future, it might also be …
>  Add an option to enable Multipath TCP on clients

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
A performance test executing 100,000 sequential requests against a simple [`NIOHTTP1Server`](https://github.com/apple/swift-nio/blob/main/Sources/NIOHTTP1Server/README.md) revealed that 7% of total run time is spent in the setter of the `request` property in `HTTP1ClientChannelHandler` (GitHub Issue #754).
The poor performance comes from [processing the string interpolation `"\(self.eventLoop)"`](https://github.com/swift-server/async-http-client/blob/6df8e1c17e68f0f93de2443b8c8cafca9ddcc89a/Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift#L39C17-L39C75) which under the hood calls a computed property.
This problem can entirely be avoided by storing `eventLoop.description` when initializing `HTTP1ClientChannelHandler`, and using that stored value in `request`'s …
> Reduce time spent logging EventLoop description in HTTP1ClientChannelHandler

- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
On modularised platforms, #771 broke things because it changed from importing `Musl` or `Glibc` to importing just `locale_h`.  The latter understandably doesn't define `errno` or `EOVERFLOW`, so we get a build failure.
Fixes #773.
> Don't just import `locale_h`.

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/DeconstructedURL.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
`Foundation.URL` has various behavior changes in Swift 6 to better match RFC 3986 which impact AHC.
In particular it now no longer strips the square brackets in IPv6 hosts which are not tolerated by `inet_pton` so these must be manually stripped.
https://github.com/swiftlang/swift-foundation/issues/957
https://github.com/swiftlang/swift-foundation/issues/958
https://github.com/swiftlang/swift-foundation/issues/962
> workaround Foundation.URL behavior changes

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+auth.swift
- Sources/AsyncHTTPClient/BasicAuth.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation:
As an HTTP library, async-http-client should have authentication support.
Modifications:
This adds a `setBasicAuth()` method to both HTTPClientRequest and `HTTPClient.Request` and their related unit tests.
Result:
Library users will be able to leverage this method to use basic authentication on their requests without implementing this in their own projects.
Note: I also ran the tests (`swift test`) with the `docker.io/library/swift:6.0-focal` and `docker.io/library/swift:5.10.1-focal` to ensure linux compatibility.
> Added: ability to set basic authentication on requests

- Package.swift
- Sources/AsyncHTTPClient/Configuration+BrowserLike.swift
- Sources/AsyncHTTPClient/ConnectionPool.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPClient+SOCKSTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientResponseTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+ManagerTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.
> Enable MemberImportVisibility check on all targets

- Package.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/EmbeddedChannel+HTTPConvenience.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
The NIO 2.78 release introduced a bunch of new warnings. These warnings cause us a bunch of trouble, so we should fix them.
Mostly use a bunch of assumeIsolated() and syncOperations.
CI passes again.
Note that Swift 6 has _many_ more warnings than this, but we expect more to come and we aren't using warnings-as-errors on that mode at the moment. We'll be cleaning that up soon.
> Unbreak CI

- Sources/AsyncHTTPClient/ConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+Backoff.swift
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
- Sources/CAsyncHTTPClient/CAsyncHTTPClient.c
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
This PR adds support for Android, mostly just by importing the Android module when needed.
> Android support

- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ConnectionStateMachine.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionStateMachineTests.swift
In some cases we can crash because of a precondition failure when the write timeout fires and we aren't in the running state. This can happen for example if the connection is closed whilst the write timer is active.
* Remove the precondition and instead take no action if the timeout fires outside of the running state. Instead we take a new `Action`, `.noAction` when the timer fires.
* Clear write timeouts upon request completion. When a request completes we have no use for the idle write timer, we clear the read timer and we should clear the write one too.
Fewer crashes.
The supplied tests fails without these changes and passes with either of them.
> Avoid precondition failure in write timeout

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
In https://github.com/swift-server/async-http-client/pull/794, the new Swift compiler feature `MemberImportVisibility` was adopted. However, CI for this project does not test building the package with the nightly compiler on macOS, so it was missed that the project no longer builds on macOS with the nightly toolchain due to a missing import.
Add `import Network` in a file that needs it.
The package builds again with the nightly toolchain on macOS.
> Add missing import of Network module

- Sources/AsyncHTTPClient/StructuredConcurrencyHelpers.swift
Specifically Swift 5.10 _on Intel on Ubuntu Noble (24.04)_ has a crazy bug which leads to compilation failures in a `#if compiler(>=6.0)` block: https://github.com/swiftlang/swift/issues/79285 .
This workaround fixes the compilation by _changing the whitespace_.
Thanks @gwynne for finding this workaround!
> fix 5.10 compile on Ubuntu 24.04 (Noble) for Intel (x86_64)

- Tests/AsyncHTTPClientTests/HTTPClient+StructuredConcurrencyTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
Motivation
EmbeddedEventLoop is not thread-safe, which means that outside of very rare use-cases it's not safe to use it in Swift Concurrency.
Modifications
Replace invalid uses of EmbeddedEventLoop with NIOAsyncTestingEventLoop
Result
Better safety
> Remove misuse of EmbeddedEventLoop

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
Foundation has reverted several of the changes of behaviour in the URL type, leaving 6.0 and 6.1 with a different behaviour on non-Apple platforms than all other versions.
We should tolerate that.
Modifications
Update the tests to understand the difference.
Result
Tests pass
> Work around Foundation revert

- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
I needed a way to use a `FileDownloadDelegate` task to fish out the recommended file name.
```swift
let response = try await downloadTask.get()
// access content-disposition
response.head.headers.first(name: "Content-Disposition")
```
The `head` property is an explicitly unwrapped optional because there is no "default value" to set it to, and it won't be accessed by the user until it's already been set anyway. This is a little inelegant, so I could change it to something like below where I fill in bogus init data, but that seems worse for some reason.
```swift
public struct Progress: Sendable {
public var totalBytes: Int?
public var receivedBytes: Int
public var head: HTTPResponseHead
}
private var progress = Progress(
totalBytes: nil,
receivedBytes: 0,
head: .init(
version: .init(major: …
```
> Add `head` property to `FileDownloadDelegate`'s `Progress`/`Response` struct

- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
Trying to pave the way for closing https://github.com/swift-server/async-http-client/issues/790 with some direction from @Lukasa.
I have no idea where is best to insert this new delegate method. I'm currently doing it first thing in `receiveResponseHead0`, and not using an EventLoopFuture for back pressure management.  The state machine seems pretty fragile and I don't want to leave too much of an imprint. Trying to be a part of an EventLoopFuture chain seems really complicated and would really leave a mark on the codebase, so I'm wondering if it's possible to just warn the user "do not block"?
Anyway, just a jumping-off point and happy to take direction!
> Add `didVisitURL` delegate method

- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Since #813, Foundation have backported their revert to 6.1. Now only 6.0 is the weird one.
> Work around Foundation revert even more

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Package.swift
- README.md
Motivation:
Now that Swift 6.1 has been released, Swift 5.9 has dropped out of the support window.
Modifications:
- Bumpt tools versions to 5.9
- Disable 5.9 workflows
Result:
5.9 is no longer supported
> Drop support for Swift 5.9

- Sources/AsyncHTTPClient/AsyncAwait/AnyAsyncSequence.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientResponse.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction+StateMachine.swift
- Sources/AsyncHTTPClient/Base64.swift
- Sources/AsyncHTTPClient/Utils.swift
Motivation:
As part of adopting strict concurrency all public types should be explicit about whether they are sendable or not.
Modifications:
- Add explicit sendability annotations to a number of types
Result:
Sendability is explicit
> Add explicit sendability annotations

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1ClientChannelHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP1/HTTP1Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2ClientRequestHandler.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTP2/HTTP2Connection.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Factory.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool.swift
- Sources/AsyncHTTPClient/ConnectionPool/HTTPExecutableRequest.swift
- Sources/AsyncHTTPClient/NIOLoopBound+Execute.swift
- Tests/AsyncHTTPClientTests/EmbeddedChannel+HTTPConvenience.swift
- Tests/AsyncHTTPClientTests/HTTP1ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ConnectionTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
- Tests/AsyncHTTPClientTests/NWWaitingHandlerTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
Motivation:
The connection pool holds much of the low level logic in AHC. We should fix its sendability issues before moving to higher levels.
Modifications:
- Make HTTP1ConnectionDelegate and HTTP2Delegate sendable, this requires passing IDs rather than connections to their methods
- Make HTTPConnectionRequester sendable and have its methods take Sendable views of the HTTP1Connection and HTTP2Connection types
- Add sendable views to HTTP1Connection and HTTP2Connection
- Mark HTTP1Connection and HTTP2Connection as not sendable
- Make HTTPRequestExecutor and HTTPExecutableRequest sendable
- Update tests
Result:
Connection pool has stricter sendability requirements
> Fix sendability issues in the connection pool

- Sources/AsyncHTTPClient/HTTPHandler.swift
Motivation:
The body stream writer can be sent across isolation domains so should be sendable.
Modifications:
- Make it explicitly sendable
- Add appropriate preconcurrency annotations
- Wrap an iterator from swift-algorithms as it hasn't yet annotated its types with Sendable
Result:
Body stream writer is sendable
> Make body stream writer sendable

- Sources/AsyncHTTPClient/FileDownloadDelegate.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
Motivation:
Delegates can be passed from any thread and are executed on an arbitrary event loop. That means they need to be Sendable. Rather than making them all Sendable in one go, we'll do the larger ones separately.
Modifications:
- Make FileDownloadDelegate sendable
Result:
Safe to pass FileDownloadDelegate across isolation domains
> Make the file download delegate sendable

- Sources/AsyncHTTPClient/HTTPClient.swift
- Sources/AsyncHTTPClient/HTTPHandler.swift
- Sources/AsyncHTTPClient/RequestBag.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
Motivation
We have some Task error handling functions that are generic for no apparent reason. They're also typically called from contexts where they also report the error to the delegate, but one of the call sites doesn't do that. So add a test for that as well.
Modifications
- Rewrite Task.fail(with:delegate:) to be non-generic.
- Add a call to the delegate error handler on the path that is missing it.
- Add a test for that call
Results
Cleaner, easier to follow code
> Clean up Task error handling.

- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest+Prepared.swift
- Sources/AsyncHTTPClient/AsyncAwait/HTTPClientRequest.swift
- Sources/AsyncHTTPClient/AsyncAwait/Transaction.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
Motivation:
There are a couple of sendability warnings leftover in Sources.
Transaction moves a closure into a task. The closure isn't Sendable (and shouldn't be). However, higher up the stack there's a closure which generates the non-sendable closure which can be sendable.
Modifications:
- Pass the sendable closure generating closure down rather
- Add a few more explicit sendable annotations
Result:
Fewer warnings
> Fix a few more Sendability warnings in Sources

- Package.swift
- Tests/AsyncHTTPClientTests/AsyncAwaitEndToEndTests.swift
- Tests/AsyncHTTPClientTests/AsyncTestHelpers.swift
- Tests/AsyncHTTPClientTests/HTTP1ClientChannelHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientRequestHandlerTests.swift
- Tests/AsyncHTTPClientTests/HTTP2ClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientInternalTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientRequestTests.swift
- Tests/AsyncHTTPClientTests/HTTPClientTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+FactoryTests.swift
- Tests/AsyncHTTPClientTests/HTTPConnectionPool+RequestQueueTests.swift
- Tests/AsyncHTTPClientTests/Mocks/MockHTTPExecutableRequest.swift
- Tests/AsyncHTTPClientTests/Mocks/MockRequestExecutor.swift
- Tests/AsyncHTTPClientTests/RequestBagTests.swift
- Tests/AsyncHTTPClientTests/SOCKSEventsHandlerTests.swift
- Tests/AsyncHTTPClientTests/SOCKSTestUtils.swift
- Tests/AsyncHTTPClientTests/TLSEventsHandlerTests.swift
- Tests/AsyncHTTPClientTests/TransactionTests.swift
Motivation:
The tests shouldn't be making sendability violations.
Modifications:
Fix the warnings
Result:
- No warnings
- Strict concurrency is adopted!
> Fix sendability issues in tests

- .github/workflows/main.yml
- .github/workflows/pull_request.yml
- Sources/AsyncHTTPClient/HTTPClient.swift
- Tests/AsyncHTTPClientTests/HTTPClientTestUtils.swift
Motivation:
Now that strict concurrency has been adopted the AHC should avoid regressing by treating all warnings as errors in CI.
Modifications:
- Treat warnings as errors in CI
Result:
Stricter CI
> Enable warnings as errors in CI

- .github/workflows/pull_request.yml
- Sources/AsyncHTTPClient/HTTPClient+HTTPCookie.swift
Motivation:
An oversight in 373862a meant that 5.9 wasn't actually dropped which means that the use of 'nonisolated(unsafe)' in 0e715a27 broke users of 5.9.
Modifications:
- Add back a 5.9 path
Result:
- Builds on 5.9
- Resolves #843
> Fix 5.9 build

- Sources/AsyncHTTPClient/ConnectionPool/State Machine/HTTPConnectionPool+Backoff.swift
Fixes #847. 
Motivation:
On 32-bit systems, using .randomElement on a range larger than what can fit in Int32 (Int) causes a crash. After only 26 or 27 retries of a request using HTTPClient, the calculateBackoff method would run into this and crash consistently on an armv7 (32-bit) device.
Modifications:
A one-line fix to opt to using Int64.random on the same jitterRange instead of .randomElement, which works as expected without crashing on 32-bit systems.
Result:
The HTTPClient now works as expected and can perform as many retries as needed without crashing.
I tested this on my armv7 board doing the retries, and ran up to several hundred repetitions after a few hours with no crashes as was happening before.
@Lukasa
> Use Int64.random instead of .randomElement in HTTPConnectionPool.calculateBackoff

- Sources/AsyncHTTPClient/ConnectionPool/HTTPConnectionPool+Manager.swift
- Sources/AsyncHTTPClient/HTTPClient.swift
Previously, `HTTPClient` used `@unchecked Sendable`, now it's compiler checked.
> make HTTPClient Sendable without @unchecked

- Sources/AsyncHTTPClient/ConnectionPool.swift
Motivation:
The trailing space is visible in log message metadata, and depending upon the log handler in use, will sometimes be visible due to quoting.
Modifications:
Just remove the trailing space.
Result:
There won't be a trailing space in the key anymore. This has no functional impact whatsoever as far as I was able to determine.
> Fix trailing space in ConnectionPool.Key string
